/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HarnessPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian16 = require("obsidian");

// src/types.ts
var DEFAULT_PROVIDERS = [
  {
    id: "openrouter",
    name: "OpenRouter",
    type: "openrouter",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeySecretName: "oh_bot_secret_openrouter",
    models: [
      "anthropic/claude-3.7-sonnet",
      "anthropic/claude-3.5-haiku",
      "openai/gpt-4o",
      "openai/gpt-4o-mini",
      "deepseek/deepseek-r1",
      "google/gemini-2.5-flash",
      "meta-llama/llama-3.3-70b-instruct"
    ],
    enabled: true
  },
  {
    id: "anthropic",
    name: "Anthropic",
    type: "anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    apiKeySecretName: "oh_bot_secret_anthropic",
    models: [
      "claude-3-7-sonnet-20250219",
      "claude-3-5-sonnet-20241022",
      "claude-3-5-haiku-20241022"
    ],
    enabled: true
  },
  {
    id: "gemini",
    name: "Google Gemini (AI Studio)",
    type: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai/",
    apiKeySecretName: "oh_bot_secret_gemini",
    models: [
      "gemini-2.5-flash",
      "gemini-2.5-pro",
      "gemini-2.0-flash",
      "gemini-1.5-pro",
      "gemini-1.5-flash"
    ],
    enabled: true
  },
  {
    id: "openai",
    name: "OpenAI",
    type: "openai",
    baseUrl: "https://api.openai.com/v1",
    apiKeySecretName: "oh_bot_secret_openai",
    models: [
      "gpt-4o",
      "gpt-4o-mini",
      "gpt-4.5-preview",
      "o3-mini",
      "o1"
    ],
    enabled: true
  },
  {
    id: "ollama",
    name: "Ollama (Local)",
    type: "ollama",
    baseUrl: "http://localhost:11434/v1",
    apiKeySecretName: "oh_bot_secret_ollama",
    models: [
      "llama3.3",
      "qwen2.5-coder",
      "deepseek-r1",
      "mistral"
    ],
    enabled: true
  }
];
var DEFAULT_SETTINGS = {
  providers: DEFAULT_PROVIDERS,
  activeProviderId: "",
  activeModel: "",
  systemPrompt: "You are an autonomous AI Agent inside Obsidian. You have tools to read, create, patch, search, and inspect notes in the vault. Use these tools step-by-step to fulfill the user request.",
  safetyMode: "strict",
  sessions: [],
  currentSessionId: ""
};

// src/ui/settings-tab.ts
var import_obsidian4 = require("obsidian");

// src/ui/components/add-provider-modal.ts
var import_obsidian2 = require("obsidian");

// src/utils/model-fetcher.ts
var import_obsidian = require("obsidian");
async function fetchAvailableModels(baseUrl, apiKey) {
  try {
    let cleanBase = baseUrl.replace(/\/+$/, "");
    if (!cleanBase.endsWith("/models")) {
      cleanBase = cleanBase + "/models";
    }
    const headers = {
      "Content-Type": "application/json"
    };
    if (apiKey) {
      headers["Authorization"] = `Bearer ${apiKey}`;
    }
    const res = await (0, import_obsidian.requestUrl)({
      url: cleanBase,
      method: "GET",
      headers
    });
    const data = res.json;
    if (data && Array.isArray(data.data)) {
      return data.data.map((m) => m.id || m.name).filter((id) => typeof id === "string").sort();
    } else if (Array.isArray(data)) {
      return data.map((m) => typeof m === "string" ? m : m.id || m.name).filter((id) => typeof id === "string").sort();
    }
    return [];
  } catch (err) {
    console.error("Failed to fetch models from endpoint:", err);
    return [];
  }
}

// src/utils/secrets.ts
var SecretManager = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Retrieves the secret value associated with the given secret name using SecretStorage API or fallback.
   */
  getSecret(secretName) {
    if (!secretName) {
      return null;
    }
    const secretStorage = this.app.secretStorage;
    if (secretStorage && typeof secretStorage.getSecret === "function") {
      const secret = secretStorage.getSecret(secretName);
      if (secret)
        return secret;
    }
    try {
      const localVal = window.localStorage.getItem(`oh_bot_${secretName}`);
      if (localVal)
        return localVal;
    } catch (e) {
    }
    return null;
  }
  /**
   * Stores secret value in SecretStorage and local storage fallback.
   */
  setSecret(secretName, value) {
    if (!secretName)
      return;
    const secretStorage = this.app.secretStorage;
    if (secretStorage && typeof secretStorage.setSecret === "function") {
      secretStorage.setSecret(secretName, value);
    }
    try {
      if (value) {
        window.localStorage.setItem(`oh_bot_${secretName}`, value);
      } else {
        window.localStorage.removeItem(`oh_bot_${secretName}`);
      }
    } catch (e) {
    }
  }
  /**
   * Checks if a secret is present and non-empty.
   */
  hasSecret(secretName) {
    const val = this.getSecret(secretName);
    return !!val && val.trim().length > 0;
  }
};

// src/ui/components/add-provider-modal.ts
var AddProviderModal = class extends import_obsidian2.Modal {
  constructor(app, onAdd) {
    super(app);
    this.providerName = "";
    this.baseUrl = "https://api.openai.com/v1";
    this.apiKey = "";
    this.models = [];
    this.onAdd = onAdd;
    this.secretManager = new SecretManager(app);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("harness-modal-content");
    contentEl.createEl("h2", { text: "Add Custom OpenAI-Compatible Provider" });
    new import_obsidian2.Setting(contentEl).setName("Provider Name").setDesc("e.g. DeepSeek, Groq, Together AI, LM Studio").addText(
      (text) => text.setPlaceholder("My Custom Provider").onChange((val) => {
        this.providerName = val.trim();
      })
    );
    new import_obsidian2.Setting(contentEl).setName("Base URL").setDesc("API Base URL (e.g. https://api.deepseek.com/v1 or http://localhost:1234/v1)").addText(
      (text) => text.setValue(this.baseUrl).onChange((val) => {
        this.baseUrl = val.trim();
      })
    );
    new import_obsidian2.Setting(contentEl).setName("API Key").setDesc("API Key will be automatically stored in Obsidian SecretStorage").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("Enter API Key").onChange((val) => {
        this.apiKey = val.trim();
      });
    });
    const modelsSetting = new import_obsidian2.Setting(contentEl).setName("Available Models").setDesc("List of models available on this provider").addTextArea((text) => {
      text.setPlaceholder("model-name-1, model-name-2").setValue(this.models.join(", ")).onChange((val) => {
        this.models = val.split(",").map((m) => m.trim()).filter((m) => m.length > 0);
      });
    });
    modelsSetting.addButton((btn) => {
      btn.setTooltip("Fetch Models from Endpoint");
      (0, import_obsidian2.setIcon)(btn.buttonEl, "refresh-cw");
      btn.onClick(async () => {
        new import_obsidian2.Notice("Fetching models from endpoint...");
        const fetched = await fetchAvailableModels(this.baseUrl, this.apiKey);
        if (fetched.length > 0) {
          this.models = fetched;
          new import_obsidian2.Notice(`Found ${fetched.length} models!`);
          this.onOpen();
        } else {
          new import_obsidian2.Notice("Could not fetch models automatically. Please specify model names manually.");
        }
      });
    });
    new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Save Provider").setCta().onClick(async () => {
        if (!this.providerName) {
          new import_obsidian2.Notice("Please enter a provider name.");
          return;
        }
        const uniqueId = `custom_${Date.now()}`;
        const secretId = `oh_bot_secret_${uniqueId}`;
        if (this.apiKey) {
          this.secretManager.setSecret(secretId, this.apiKey);
        }
        const newProvider = {
          id: uniqueId,
          name: this.providerName,
          type: "custom-openai",
          baseUrl: this.baseUrl,
          apiKeySecretName: secretId,
          models: this.models.length > 0 ? this.models : ["default-model"],
          enabled: true,
          isCustom: true
        };
        await this.onAdd(newProvider);
        new import_obsidian2.Notice(`Provider "${this.providerName}" added!`);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/ui/components/edit-models-modal.ts
var import_obsidian3 = require("obsidian");
var EditModelsModal = class extends import_obsidian3.Modal {
  constructor(app, provider, onSave) {
    super(app);
    this.provider = provider;
    this.models = [...provider.models];
    this.onSave = onSave;
  }
  onOpen() {
    this.render();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("harness-modal-content");
    contentEl.createEl("h2", { text: `Edit Models: ${this.provider.name}` });
    contentEl.createEl("p", {
      text: "Manage, edit, or remove individual models for this provider.",
      cls: "setting-item-description"
    });
    const listContainerEl = contentEl.createEl("div", { cls: "harness-models-edit-list" });
    listContainerEl.style.display = "flex";
    listContainerEl.style.flexDirection = "column";
    listContainerEl.style.gap = "8px";
    listContainerEl.style.maxHeight = "280px";
    listContainerEl.style.overflowY = "auto";
    listContainerEl.style.padding = "4px";
    listContainerEl.style.marginBottom = "12px";
    if (this.models.length === 0) {
      listContainerEl.createEl("div", { text: "No models configured yet.", cls: "setting-item-description" });
    }
    this.models.forEach((modelName, index) => {
      const rowEl = listContainerEl.createEl("div", { cls: "harness-model-row" });
      rowEl.style.display = "flex";
      rowEl.style.alignItems = "center";
      rowEl.style.gap = "8px";
      const input = rowEl.createEl("input", { type: "text", value: modelName });
      input.style.flex = "1";
      input.addEventListener("change", (e) => {
        const val = e.target.value.trim();
        if (val) {
          this.models[index] = val;
        }
      });
      const delBtn = rowEl.createEl("button", { cls: "harness-btn-icon-round" });
      (0, import_obsidian3.setIcon)(delBtn, "trash");
      delBtn.setAttribute("aria-label", "Delete model");
      delBtn.addEventListener("click", () => {
        this.models.splice(index, 1);
        this.render();
      });
    });
    const addRowEl = contentEl.createEl("div");
    addRowEl.style.display = "flex";
    addRowEl.style.gap = "8px";
    addRowEl.style.marginBottom = "16px";
    const addInput = addRowEl.createEl("input", {
      type: "text",
      placeholder: "Enter new model identifier (e.g. gpt-4o, claude-3-5-haiku)"
    });
    addInput.style.flex = "1";
    const addBtn = addRowEl.createEl("button", { text: " Add Model" });
    (0, import_obsidian3.setIcon)(addBtn, "plus");
    const handleAdd = () => {
      const val = addInput.value.trim();
      if (!val) {
        new import_obsidian3.Notice("Please enter a model identifier.");
        return;
      }
      if (!this.models.includes(val)) {
        this.models.push(val);
        this.render();
      } else {
        new import_obsidian3.Notice("This model already exists in the list.");
      }
    };
    addBtn.addEventListener("click", handleAdd);
    addInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        handleAdd();
      }
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Save Changes").setCta().onClick(async () => {
        const cleanModels = this.models.map((m) => m.trim()).filter((m) => m.length > 0);
        await this.onSave(cleanModels);
        new import_obsidian3.Notice(`Models updated for ${this.provider.name}`);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/ui/settings-tab.ts
var HarnessSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.secretManager = new SecretManager(app);
    this.selectedConfigProviderId = this.plugin.settings.activeProviderId || this.plugin.settings.providers[0]?.id || "openrouter";
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("harness-settings-container");
    containerEl.createEl("h2", { text: "Obsidian Harness Bot Settings" });
    new import_obsidian4.Setting(containerEl).setName("Default Active Provider").setDesc("Select the default AI provider for agent operations").addDropdown((dropdown) => {
      dropdown.addOption("", "(Not configured)");
      for (const prov of this.plugin.settings.providers) {
        const hasKey = prov.type === "ollama" || this.secretManager.hasSecret(prov.apiKeySecretName);
        const label = hasKey ? prov.name : `${prov.name} (Key missing)`;
        dropdown.addOption(prov.id, label);
      }
      dropdown.setValue(this.plugin.settings.activeProviderId || "");
      dropdown.onChange(async (val) => {
        this.plugin.settings.activeProviderId = val;
        const activeProv = this.plugin.settings.providers.find((p) => p.id === val);
        if (activeProv && activeProv.models.length > 0) {
          this.plugin.settings.activeModel = activeProv.models[0];
        } else {
          this.plugin.settings.activeModel = "";
        }
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const currentActiveProvider = this.plugin.settings.providers.find(
      (p) => p.id === this.plugin.settings.activeProviderId
    );
    const modelSetting = new import_obsidian4.Setting(containerEl).setName("Default Active Model").setDesc(currentActiveProvider ? `Select model for ${currentActiveProvider.name}` : "Select an active provider first");
    if (currentActiveProvider && currentActiveProvider.models.length > 0) {
      modelSetting.addDropdown((dropdown) => {
        for (const m of currentActiveProvider.models) {
          dropdown.addOption(m, m);
        }
        if (currentActiveProvider.models.includes(this.plugin.settings.activeModel)) {
          dropdown.setValue(this.plugin.settings.activeModel);
        } else {
          dropdown.setValue(currentActiveProvider.models[0]);
          this.plugin.settings.activeModel = currentActiveProvider.models[0];
        }
        dropdown.onChange(async (val) => {
          this.plugin.settings.activeModel = val;
          await this.plugin.saveSettings();
        });
      });
    } else {
      modelSetting.addDropdown((dropdown) => {
        dropdown.addOption("", "(No models configured)");
        dropdown.setValue("");
      });
    }
    containerEl.createEl("h3", { text: "Provider Configuration" });
    const providerSelectSetting = new import_obsidian4.Setting(containerEl).setName("Select Provider to Configure").setDesc("Choose a provider to configure its API key, base URL, and model list").addDropdown((dropdown) => {
      for (const prov of this.plugin.settings.providers) {
        dropdown.addOption(prov.id, prov.name);
      }
      dropdown.setValue(this.selectedConfigProviderId);
      dropdown.onChange((val) => {
        this.selectedConfigProviderId = val;
        this.display();
      });
    });
    providerSelectSetting.addButton((btn) => {
      btn.setButtonText("+ Custom Provider");
      btn.setCta();
      btn.onClick(() => {
        new AddProviderModal(this.app, async (newProvider) => {
          this.plugin.settings.providers.push(newProvider);
          this.selectedConfigProviderId = newProvider.id;
          if (!this.plugin.settings.activeProviderId) {
            this.plugin.settings.activeProviderId = newProvider.id;
            this.plugin.settings.activeModel = newProvider.models[0] || "";
          }
          await this.plugin.saveSettings();
          this.display();
        }).open();
      });
    });
    const configProvider = this.plugin.settings.providers.find(
      (p) => p.id === this.selectedConfigProviderId
    );
    if (configProvider) {
      const providerCardEl = containerEl.createEl("div", { cls: "harness-provider-card" });
      providerCardEl.style.border = "1px solid var(--background-modifier-border)";
      providerCardEl.style.borderRadius = "8px";
      providerCardEl.style.padding = "12px";
      providerCardEl.style.marginBottom = "16px";
      providerCardEl.style.backgroundColor = "var(--background-secondary)";
      providerCardEl.createEl("h4", { text: `Configuration: ${configProvider.name}` });
      new import_obsidian4.Setting(providerCardEl).setName("Base URL").setDesc("API Endpoint URL").addText(
        (text) => text.setValue(configProvider.baseUrl).onChange(async (val) => {
          configProvider.baseUrl = val.trim();
          await this.plugin.saveSettings();
        })
      );
      const hasKey = this.secretManager.hasSecret(configProvider.apiKeySecretName);
      const keySetting = new import_obsidian4.Setting(providerCardEl).setName("API Key").setDesc(hasKey ? "Key is configured in SecretStorage" : "Enter API Key to store securely");
      keySetting.addText((text) => {
        text.inputEl.type = "password";
        text.setPlaceholder(hasKey ? "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022" : "Enter API Key");
        text.onChange(async (val) => {
          const trimmed = val.trim();
          if (trimmed) {
            this.secretManager.setSecret(configProvider.apiKeySecretName, trimmed);
            if (!this.plugin.settings.activeProviderId) {
              this.plugin.settings.activeProviderId = configProvider.id;
              this.plugin.settings.activeModel = configProvider.models[0] || "";
            }
            await this.plugin.saveSettings();
            new import_obsidian4.Notice(`API Key saved for ${configProvider.name}`);
          }
        });
      });
      if (hasKey) {
        keySetting.addButton((btn) => {
          btn.setButtonText("Clear Key");
          btn.setWarning();
          btn.onClick(async () => {
            this.secretManager.setSecret(configProvider.apiKeySecretName, "");
            new import_obsidian4.Notice(`API Key cleared for ${configProvider.name}`);
            this.display();
          });
        });
      }
      const modelsSetting = new import_obsidian4.Setting(providerCardEl).setName("Available Models").setDesc(`${configProvider.models.length} model(s) configured`);
      if (configProvider.models.length > 0) {
        modelsSetting.addDropdown((dropdown) => {
          for (const m of configProvider.models) {
            dropdown.addOption(m, m);
          }
          dropdown.setValue(configProvider.models[0]);
        });
      } else {
        modelsSetting.addDropdown((dropdown) => {
          dropdown.addOption("", "(No models loaded)");
        });
      }
      modelsSetting.addButton((btn) => {
        btn.setClass("harness-btn-icon-round");
        btn.setTooltip("Fetch models from endpoint");
        (0, import_obsidian4.setIcon)(btn.buttonEl, "refresh-cw");
        btn.onClick(async () => {
          const apiKey = this.secretManager.getSecret(configProvider.apiKeySecretName) || "";
          new import_obsidian4.Notice(`Fetching models for ${configProvider.name}...`);
          const fetched = await fetchAvailableModels(configProvider.baseUrl, apiKey);
          if (fetched.length > 0) {
            configProvider.models = fetched;
            if (this.plugin.settings.activeProviderId === configProvider.id && fetched.length > 0) {
              this.plugin.settings.activeModel = fetched[0];
            }
            await this.plugin.saveSettings();
            new import_obsidian4.Notice(`Updated ${configProvider.name} with ${fetched.length} models!`);
            this.display();
          } else {
            new import_obsidian4.Notice("Could not fetch models automatically from endpoint.");
          }
        });
      });
      modelsSetting.addButton((btn) => {
        btn.setClass("harness-btn-icon-round");
        btn.setTooltip("Edit models list");
        (0, import_obsidian4.setIcon)(btn.buttonEl, "pencil");
        btn.onClick(() => {
          new EditModelsModal(this.app, configProvider, async (updatedModels) => {
            configProvider.models = updatedModels;
            if (this.plugin.settings.activeProviderId === configProvider.id) {
              if (!updatedModels.includes(this.plugin.settings.activeModel)) {
                this.plugin.settings.activeModel = updatedModels[0] || "";
              }
            }
            await this.plugin.saveSettings();
            this.display();
          }).open();
        });
      });
      if (configProvider.isCustom) {
        const deleteSetting = new import_obsidian4.Setting(providerCardEl).setName("Delete Provider").setDesc("Remove this custom provider from settings");
        deleteSetting.addButton((btn) => {
          btn.setButtonText("Delete Provider");
          (0, import_obsidian4.setIcon)(btn.buttonEl, "trash");
          btn.setWarning();
          btn.onClick(async () => {
            this.plugin.settings.providers = this.plugin.settings.providers.filter(
              (p) => p.id !== configProvider.id
            );
            this.selectedConfigProviderId = this.plugin.settings.providers[0]?.id || "openrouter";
            if (this.plugin.settings.activeProviderId === configProvider.id) {
              this.plugin.settings.activeProviderId = "";
              this.plugin.settings.activeModel = "";
            }
            await this.plugin.saveSettings();
            new import_obsidian4.Notice(`Deleted provider "${configProvider.name}".`);
            this.display();
          });
        });
      }
    }
    containerEl.createEl("h3", { text: "General & Safety" });
    new import_obsidian4.Setting(containerEl).setName("Vault Modification Safety Mode").setDesc("Strict mode prompts for user confirmation before writing or modifying any Vault file").addDropdown(
      (dropdown) => dropdown.addOption("strict", "Strict (Prompt before file edits)").addOption("auto", "Auto (Auto-approve file edits)").setValue(this.plugin.settings.safetyMode).onChange(async (value) => {
        this.plugin.settings.safetyMode = value;
        await this.plugin.saveSettings();
      })
    );
    const promptSetting = new import_obsidian4.Setting(containerEl).setName("System Prompt").setDesc("Base instructions for the Agent Harness");
    promptSetting.setClass("harness-fullwidth-setting");
    promptSetting.addTextArea((text) => {
      text.inputEl.addClass("harness-fullwidth-textarea");
      text.setValue(this.plugin.settings.systemPrompt);
      const autoResize = () => {
        text.inputEl.style.height = "auto";
        text.inputEl.style.height = Math.max(140, text.inputEl.scrollHeight + 8) + "px";
      };
      setTimeout(autoResize, 20);
      text.inputEl.addEventListener("input", autoResize);
      text.onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
        autoResize();
      });
    });
  }
};

// src/ui/chat-view.ts
var import_obsidian15 = require("obsidian");

// src/engine/providers/base.ts
var LLMProvider = class {
};

// src/utils/cache-helpers.ts
function sortToolSchemasDeterministically(tools) {
  return [...tools].sort((a, b) => a.name.localeCompare(b.name)).map((tool) => {
    const properties = tool.parameters.properties;
    const sortedPropertyKeys = Object.keys(properties).sort();
    const sortedProperties = {};
    for (const key of sortedPropertyKeys) {
      sortedProperties[key] = properties[key];
    }
    return {
      ...tool,
      parameters: {
        ...tool.parameters,
        properties: sortedProperties,
        required: tool.parameters.required ? [...tool.parameters.required].sort() : void 0
      }
    };
  });
}
function prepareNetworkPayloadMessages(messages) {
  if (messages.length === 0)
    return [];
  const networkMessages = JSON.parse(JSON.stringify(messages));
  for (let i = networkMessages.length - 1; i >= 0; i--) {
    if (networkMessages[i].role === "user" && typeof networkMessages[i].content === "string") {
      const nowIso = (/* @__PURE__ */ new Date()).toISOString();
      networkMessages[i].content = `${networkMessages[i].content}

[Current Date & Time: ${nowIso}]`;
      break;
    }
  }
  return networkMessages;
}

// src/engine/stream-parser.ts
var SSEStreamParser = class {
  constructor() {
    this.buffer = "";
  }
  /**
   * Processes a chunk of string text and extracts completed SSE event lines.
   */
  feed(chunk) {
    this.buffer += chunk;
    const events = [];
    const lines = this.buffer.split("\n");
    this.buffer = lines.pop() || "";
    let currentEvent = {};
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) {
        if (currentEvent.data !== void 0) {
          events.push(currentEvent);
          currentEvent = {};
        }
        continue;
      }
      if (trimmed.startsWith("event:")) {
        currentEvent.event = trimmed.substring(6).trim();
      } else if (trimmed.startsWith("data:")) {
        const dataPart = trimmed.substring(5).trim();
        if (currentEvent.data) {
          currentEvent.data += "\n" + dataPart;
        } else {
          currentEvent.data = dataPart;
        }
      }
    }
    return events;
  }
};

// src/engine/providers/openrouter.ts
var import_obsidian5 = require("obsidian");
var OpenRouterProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "openrouter";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk, signal) {
    const endpoint = (baseUrl || "https://openrouter.ai/api/v1").replace(/\/$/, "") + "/chat/completions";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = [
      { role: "system", content: systemPrompt },
      ...networkMessages
    ];
    const formattedTools = sortedTools.map((t) => ({
      type: "function",
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }));
    const payload = {
      model: model || "anthropic/claude-3.7-sonnet",
      messages: formattedMessages,
      stream: true
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`,
          "HTTP-Referer": "https://github.com/killeryStark/oh-bot",
          "X-Title": "Obsidian Harness Bot"
        },
        body: JSON.stringify(payload),
        signal
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`OpenRouter HTTP ${response.status}: ${errorText}`);
      }
      const reader = response.body?.getReader();
      const decoder = new TextDecoder("utf-8");
      const parser = new SSEStreamParser();
      let fullContent = "";
      const toolCallMap = {};
      if (reader) {
        while (true) {
          if (signal?.aborted) {
            reader.cancel();
            break;
          }
          const { done, value } = await reader.read();
          if (done)
            break;
          const text = decoder.decode(value, { stream: true });
          const events = parser.feed(text);
          for (const ev of events) {
            if (ev.data === "[DONE]")
              continue;
            try {
              const parsed = JSON.parse(ev.data);
              const delta = parsed.choices?.[0]?.delta;
              if (delta?.content) {
                fullContent += delta.content;
                if (onChunk)
                  onChunk(delta.content);
              }
              if (delta?.tool_calls) {
                for (const tc of delta.tool_calls) {
                  const idx = tc.index ?? 0;
                  if (!toolCallMap[idx]) {
                    toolCallMap[idx] = { id: tc.id || "", name: tc.function?.name || "", args: "" };
                  }
                  if (tc.id)
                    toolCallMap[idx].id = tc.id;
                  if (tc.function?.name)
                    toolCallMap[idx].name = tc.function.name;
                  if (tc.function?.arguments)
                    toolCallMap[idx].args += tc.function.arguments;
                }
              }
            } catch (e) {
            }
          }
        }
      }
      const finalToolCalls = Object.values(toolCallMap).map((tc) => ({
        id: tc.id,
        type: "function",
        function: {
          name: tc.name,
          arguments: tc.args
        }
      }));
      return {
        content: fullContent,
        toolCalls: finalToolCalls.length > 0 ? finalToolCalls : void 0
      };
    } catch (err) {
      if (signal?.aborted || err.name === "AbortError") {
        throw new Error("Generation stopped by user.");
      }
      const reqRes = await (0, import_obsidian5.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({ ...payload, stream: false })
      });
      const resJson = reqRes.json;
      const choice = resJson.choices?.[0]?.message;
      return {
        content: choice?.content || "",
        toolCalls: choice?.tool_calls
      };
    }
  }
};

// src/engine/providers/openai.ts
var import_obsidian6 = require("obsidian");
var OpenAIProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "openai";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk, signal) {
    const endpoint = (baseUrl || "https://api.openai.com/v1").replace(/\/$/, "") + "/chat/completions";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = [
      { role: "system", content: systemPrompt },
      ...networkMessages
    ];
    const formattedTools = sortedTools.map((t) => ({
      type: "function",
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }));
    const payload = {
      model: model || "gpt-4o",
      messages: formattedMessages,
      stream: true
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify(payload),
        signal
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`OpenAI HTTP ${response.status}: ${errorText}`);
      }
      const reader = response.body?.getReader();
      const decoder = new TextDecoder("utf-8");
      const parser = new SSEStreamParser();
      let fullContent = "";
      const toolCallMap = {};
      if (reader) {
        while (true) {
          if (signal?.aborted) {
            reader.cancel();
            break;
          }
          const { done, value } = await reader.read();
          if (done)
            break;
          const text = decoder.decode(value, { stream: true });
          const events = parser.feed(text);
          for (const ev of events) {
            if (ev.data === "[DONE]")
              continue;
            try {
              const parsed = JSON.parse(ev.data);
              const delta = parsed.choices?.[0]?.delta;
              if (delta?.content) {
                fullContent += delta.content;
                if (onChunk)
                  onChunk(delta.content);
              }
              if (delta?.tool_calls) {
                for (const tc of delta.tool_calls) {
                  const idx = tc.index ?? 0;
                  if (!toolCallMap[idx]) {
                    toolCallMap[idx] = { id: tc.id || "", name: tc.function?.name || "", args: "" };
                  }
                  if (tc.id)
                    toolCallMap[idx].id = tc.id;
                  if (tc.function?.name)
                    toolCallMap[idx].name = tc.function.name;
                  if (tc.function?.arguments)
                    toolCallMap[idx].args += tc.function.arguments;
                }
              }
            } catch (e) {
            }
          }
        }
      }
      const finalToolCalls = Object.values(toolCallMap).map((tc) => ({
        id: tc.id,
        type: "function",
        function: {
          name: tc.name,
          arguments: tc.args
        }
      }));
      return {
        content: fullContent,
        toolCalls: finalToolCalls.length > 0 ? finalToolCalls : void 0
      };
    } catch (err) {
      if (signal?.aborted || err.name === "AbortError") {
        throw new Error("Generation stopped by user.");
      }
      const reqRes = await (0, import_obsidian6.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({ ...payload, stream: false })
      });
      const resJson = reqRes.json;
      const choice = resJson.choices?.[0]?.message;
      return {
        content: choice?.content || "",
        toolCalls: choice?.tool_calls
      };
    }
  }
};

// src/engine/providers/anthropic.ts
var import_obsidian7 = require("obsidian");
var AnthropicProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "anthropic";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk, signal) {
    const endpoint = (baseUrl || "https://api.anthropic.com/v1").replace(/\/$/, "") + "/messages";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = networkMessages.map((msg) => ({
      role: msg.role === "assistant" ? "assistant" : "user",
      content: msg.content
    }));
    const formattedTools = sortedTools.map((t) => ({
      name: t.name,
      description: t.description,
      input_schema: t.parameters
    }));
    const payload = {
      model: model || "claude-3-7-sonnet-20250219",
      max_tokens: 4096,
      system: [
        {
          type: "text",
          text: systemPrompt,
          cache_control: { type: "ephemeral" }
        }
      ],
      messages: formattedMessages,
      stream: true
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01",
          "anthropic-beta": "prompt-caching-2024-07-31"
        },
        body: JSON.stringify(payload),
        signal
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Anthropic HTTP ${response.status}: ${errorText}`);
      }
      const reader = response.body?.getReader();
      const decoder = new TextDecoder("utf-8");
      const parser = new SSEStreamParser();
      let fullContent = "";
      const toolCallList = [];
      let currentToolCall = null;
      if (reader) {
        while (true) {
          if (signal?.aborted) {
            reader.cancel();
            break;
          }
          const { done, value } = await reader.read();
          if (done)
            break;
          const text = decoder.decode(value, { stream: true });
          const events = parser.feed(text);
          for (const ev of events) {
            try {
              const parsed = JSON.parse(ev.data);
              if (parsed.type === "content_block_delta") {
                if (parsed.delta?.type === "text_delta") {
                  const chunk = parsed.delta.text;
                  fullContent += chunk;
                  if (onChunk)
                    onChunk(chunk);
                } else if (parsed.delta?.type === "input_json_delta") {
                  if (currentToolCall) {
                    currentToolCall.argsStr += parsed.delta.partial_json;
                  }
                }
              } else if (parsed.type === "content_block_start") {
                if (parsed.content_block?.type === "tool_use") {
                  currentToolCall = {
                    id: parsed.content_block.id,
                    name: parsed.content_block.name,
                    argsStr: ""
                  };
                }
              } else if (parsed.type === "content_block_stop") {
                if (currentToolCall) {
                  toolCallList.push({
                    id: currentToolCall.id,
                    type: "function",
                    function: {
                      name: currentToolCall.name,
                      arguments: currentToolCall.argsStr
                    }
                  });
                  currentToolCall = null;
                }
              }
            } catch (e) {
            }
          }
        }
      }
      return {
        content: fullContent,
        toolCalls: toolCallList.length > 0 ? toolCallList : void 0
      };
    } catch (err) {
      if (signal?.aborted || err.name === "AbortError") {
        throw new Error("Generation stopped by user.");
      }
      const reqRes = await (0, import_obsidian7.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify({ ...payload, stream: false })
      });
      const resJson = reqRes.json;
      let textContent = "";
      const toolCalls = [];
      for (const block of resJson.content || []) {
        if (block.type === "text") {
          textContent += block.text;
        } else if (block.type === "tool_use") {
          toolCalls.push({
            id: block.id,
            type: "function",
            function: {
              name: block.name,
              arguments: JSON.stringify(block.input)
            }
          });
        }
      }
      return {
        content: textContent,
        toolCalls: toolCalls.length > 0 ? toolCalls : void 0
      };
    }
  }
};

// src/engine/providers/ollama.ts
var import_obsidian8 = require("obsidian");
var OllamaProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "ollama";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk, signal) {
    const endpoint = (baseUrl || "http://localhost:11434/v1").replace(/\/$/, "") + "/chat/completions";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = [
      { role: "system", content: systemPrompt },
      ...networkMessages
    ];
    const formattedTools = sortedTools.map((t) => ({
      type: "function",
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }));
    const payload = {
      model: model || "llama3",
      messages: formattedMessages,
      stream: false
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    const headers = {
      "Content-Type": "application/json"
    };
    if (apiKey) {
      headers["Authorization"] = `Bearer ${apiKey}`;
    }
    if (signal?.aborted) {
      throw new Error("Generation stopped by user.");
    }
    const reqRes = await (0, import_obsidian8.requestUrl)({
      url: endpoint,
      method: "POST",
      headers,
      body: JSON.stringify(payload)
    });
    const resJson = reqRes.json;
    const choice = resJson.choices?.[0]?.message;
    if (choice?.content && onChunk) {
      onChunk(choice.content);
    }
    const toolCalls = (choice?.tool_calls || []).map((tc) => ({
      id: tc.id || `call_${Date.now()}`,
      type: "function",
      function: {
        name: tc.function?.name || "",
        arguments: typeof tc.function?.arguments === "string" ? tc.function.arguments : JSON.stringify(tc.function?.arguments || {})
      }
    }));
    return {
      content: choice?.content || "",
      toolCalls: toolCalls.length > 0 ? toolCalls : void 0
    };
  }
};

// src/engine/agent.ts
var AgentHarness = class {
  constructor(app, settings, toolRegistry) {
    this.providers = /* @__PURE__ */ new Map();
    this.app = app;
    this.settings = settings;
    this.secretManager = new SecretManager(app);
    this.toolRegistry = toolRegistry;
    this.providers.set("openrouter", new OpenRouterProvider());
    this.providers.set("openai", new OpenAIProvider());
    this.providers.set("gemini", new OpenAIProvider());
    this.providers.set("custom-openai", new OpenAIProvider());
    this.providers.set("anthropic", new AnthropicProvider());
    this.providers.set("ollama", new OllamaProvider());
  }
  getActiveProviderConfig(providerId) {
    const targetId = providerId || this.settings.activeProviderId || "openrouter";
    const config = this.settings.providers.find((p) => p.id === targetId) || this.settings.providers[0];
    if (!config) {
      throw new Error(`No provider found for ID "${targetId}"`);
    }
    let provider = this.providers.get(config.type);
    if (!provider) {
      provider = this.providers.get("openai");
    }
    if (!provider) {
      throw new Error(`Unsupported provider type: ${config.type}`);
    }
    const apiKey = config.apiKeySecretName ? this.secretManager.getSecret(config.apiKeySecretName) || "" : "";
    if (config.type !== "ollama" && !apiKey) {
      throw new Error(`No API key found for provider "${config.name}". Please set it in Settings.`);
    }
    return { provider, config, apiKey };
  }
  /**
   * Runs the multi-step agent turn loop with AbortSignal support.
   */
  async runTurn(history, onEvent, onConfirm, overrideProviderId, overrideModel, signal) {
    const { provider, config, apiKey } = this.getActiveProviderConfig(overrideProviderId);
    const model = overrideModel || this.settings.activeModel || config.models[0] || "anthropic/claude-3.7-sonnet";
    const messages = [...history];
    const tools = this.toolRegistry.getSchemas();
    const maxSteps = 25;
    let step = 0;
    let keepRunning = true;
    while (keepRunning && step < maxSteps) {
      if (signal?.aborted) {
        throw new Error("Generation stopped by user.");
      }
      step++;
      let streamContent = "";
      const response = await provider.chatCompletion(
        apiKey,
        config.baseUrl,
        model,
        this.settings.systemPrompt,
        messages,
        tools,
        (chunk) => {
          if (signal?.aborted)
            return;
          streamContent += chunk;
          onEvent({
            type: "chunk",
            step,
            content: streamContent
          });
        },
        signal
      );
      if (signal?.aborted) {
        throw new Error("Generation stopped by user.");
      }
      const assistantMessage = {
        role: "assistant",
        content: response.content || "",
        tool_calls: response.toolCalls
      };
      messages.push(assistantMessage);
      if (response.toolCalls && response.toolCalls.length > 0) {
        for (const toolCall of response.toolCalls) {
          if (signal?.aborted)
            break;
          onEvent({
            type: "tool_call",
            step,
            toolCall
          });
          const toolInstance = this.toolRegistry.getTool(toolCall.function.name);
          if (toolInstance?.isMutation && this.settings.safetyMode === "strict") {
            onEvent({
              type: "awaiting_confirmation",
              step,
              toolCall
            });
            if (onConfirm) {
              const approved = await onConfirm(toolCall);
              if (!approved) {
                const cancelledResult = {
                  success: false,
                  output: "",
                  error: "User denied file modification permission for this tool execution."
                };
                messages.push({
                  role: "tool",
                  tool_call_id: toolCall.id,
                  name: toolCall.function.name,
                  content: JSON.stringify(cancelledResult)
                });
                onEvent({
                  type: "tool_result",
                  step,
                  toolResult: { toolCallId: toolCall.id, result: cancelledResult }
                });
                continue;
              }
            }
          }
          let parsedArgs = {};
          try {
            parsedArgs = JSON.parse(toolCall.function.arguments || "{}");
          } catch (e) {
            parsedArgs = {};
          }
          const result = await this.toolRegistry.executeTool(toolCall.function.name, parsedArgs, this.app);
          messages.push({
            role: "tool",
            tool_call_id: toolCall.id,
            name: toolCall.function.name,
            content: result.success ? result.output : `Error: ${result.error}`
          });
          onEvent({
            type: "tool_result",
            step,
            toolResult: { toolCallId: toolCall.id, result }
          });
        }
      } else {
        keepRunning = false;
        onEvent({
          type: "finish",
          step,
          content: response.content
        });
      }
    }
    if (step >= maxSteps) {
      onEvent({
        type: "finish",
        step,
        content: `[Agent reached maximum step limit (${maxSteps})].`
      });
    }
    return messages;
  }
};

// src/tools/base.ts
var AgentTool = class {
  constructor() {
    /**
     * Indicates whether executing this tool modifies files in the Vault and requires strict confirmation.
     */
    this.isMutation = false;
  }
  /**
   * Returns clean JSON Schema representation of the tool.
   */
  toSchema() {
    return {
      name: this.name,
      description: this.description,
      parameters: this.parameters
    };
  }
};

// src/tools/vault/read-file.ts
var import_obsidian9 = require("obsidian");
var VaultReadFileTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_read_file";
    this.description = "Reads the content of a Markdown file or text document in the Obsidian Vault by path.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: 'Relative path of the file in the Vault (e.g. "Projects/Ideas.md")'
        }
      },
      required: ["path"]
    };
    this.isMutation = false;
  }
  async execute(args, app) {
    try {
      const file = app.vault.getAbstractFileByPath(args.path);
      if (!file || !(file instanceof import_obsidian9.TFile)) {
        return {
          success: false,
          output: "",
          error: `File not found at path: ${args.path}`
        };
      }
      const content = await app.vault.read(file);
      return {
        success: true,
        output: content
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error reading file ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/create-file.ts
var VaultCreateFileTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_create_file";
    this.description = "Creates a new Markdown file or document in the Vault at the specified path with initial content.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: 'Relative path for the new file in the Vault (e.g. "Notes/Daily-2026-08-13.md")'
        },
        content: {
          type: "string",
          description: "Text content to write into the new file"
        }
      },
      required: ["path", "content"]
    };
    this.isMutation = true;
  }
  async execute(args, app) {
    try {
      const existing = app.vault.getAbstractFileByPath(args.path);
      if (existing) {
        return {
          success: false,
          output: "",
          error: `A file or folder already exists at path: ${args.path}. Use vault_patch_file to modify existing files.`
        };
      }
      const pathParts = args.path.split("/");
      if (pathParts.length > 1) {
        const folderPath = pathParts.slice(0, -1).join("/");
        const folder = app.vault.getAbstractFileByPath(folderPath);
        if (!folder) {
          await app.vault.createFolder(folderPath);
        }
      }
      const createdFile = await app.vault.create(args.path, args.content || "");
      return {
        success: true,
        output: `File successfully created at ${createdFile.path} (${createdFile.stat.size} bytes).`
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error creating file ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/patch-file.ts
var import_obsidian10 = require("obsidian");
var VaultPatchFileTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_patch_file";
    this.description = "Updates or appends content to an existing file in the Vault.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: "Relative path of the existing file to update"
        },
        content: {
          type: "string",
          description: "New content to write or append"
        },
        mode: {
          type: "string",
          enum: ["overwrite", "append"],
          description: 'Mode of update: "overwrite" replaces entire content, "append" adds to the end of the file'
        }
      },
      required: ["path", "content", "mode"]
    };
    this.isMutation = true;
  }
  async execute(args, app) {
    try {
      const file = app.vault.getAbstractFileByPath(args.path);
      if (!file || !(file instanceof import_obsidian10.TFile)) {
        return {
          success: false,
          output: "",
          error: `File not found at path: ${args.path}`
        };
      }
      if (args.mode === "append") {
        await app.vault.append(file, "\n" + args.content);
        return {
          success: true,
          output: `Successfully appended content to ${file.path}.`
        };
      } else {
        await app.vault.modify(file, args.content);
        return {
          success: true,
          output: `Successfully overwritten content of ${file.path}.`
        };
      }
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error patching file ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/list-dir.ts
var import_obsidian11 = require("obsidian");
var VaultListDirTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_list_dir";
    this.description = "Lists all files and subfolders within a given Vault folder path.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: 'Relative path of the directory (use "" or "/" for root directory)'
        }
      },
      required: ["path"]
    };
    this.isMutation = false;
  }
  async execute(args, app) {
    try {
      const folderPath = (args.path || "").replace(/^\//, "");
      const folder = folderPath === "" ? app.vault.getRoot() : app.vault.getAbstractFileByPath(folderPath);
      if (!folder || !(folder instanceof import_obsidian11.TFolder)) {
        return {
          success: false,
          output: "",
          error: `Directory not found at path: "${args.path}"`
        };
      }
      const items = folder.children.map((child) => ({
        name: child.name,
        path: child.path,
        type: child instanceof import_obsidian11.TFolder ? "folder" : "file"
      }));
      return {
        success: true,
        output: JSON.stringify(items, null, 2)
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error listing directory ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/search-notes.ts
var VaultSearchNotesTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_search_notes";
    this.description = "Searches for notes in the Vault matching a search query string or keyword.";
    this.parameters = {
      type: "object",
      properties: {
        query: {
          type: "string",
          description: "Keyword or tag to search for in note paths or titles"
        }
      },
      required: ["query"]
    };
    this.isMutation = false;
  }
  async execute(args, app) {
    try {
      const queryLower = (args.query || "").toLowerCase();
      const files = app.vault.getMarkdownFiles();
      const matched = files.filter((file) => file.path.toLowerCase().includes(queryLower) || file.basename.toLowerCase().includes(queryLower)).map((file) => ({
        name: file.name,
        path: file.path,
        size: file.stat.size,
        mtime: file.stat.mtime
      })).slice(0, 20);
      return {
        success: true,
        output: JSON.stringify(matched, null, 2)
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error searching notes for "${args.query}": ${e.message}`
      };
    }
  }
};

// src/tools/registry.ts
var ToolRegistry = class {
  constructor() {
    this.tools = /* @__PURE__ */ new Map();
    this.registerTool(new VaultReadFileTool());
    this.registerTool(new VaultCreateFileTool());
    this.registerTool(new VaultPatchFileTool());
    this.registerTool(new VaultListDirTool());
    this.registerTool(new VaultSearchNotesTool());
  }
  registerTool(tool) {
    this.tools.set(tool.name, tool);
  }
  getTool(name) {
    return this.tools.get(name);
  }
  /**
   * Returns all registered tools as deterministically sorted ToolSchemas.
   */
  getSchemas() {
    const rawSchemas = Array.from(this.tools.values()).map((t) => t.toSchema());
    return sortToolSchemasDeterministically(rawSchemas);
  }
  async executeTool(name, args, app) {
    const tool = this.getTool(name);
    if (!tool) {
      return {
        success: false,
        output: "",
        error: `Unknown tool name: "${name}"`
      };
    }
    return await tool.execute(args, app);
  }
};

// src/utils/markdown-exporter.ts
var MarkdownExporter = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Exports conversation history to a formatted Markdown note in the "Agent Chats/" Vault folder.
   */
  async exportChatToMarkdown(messages, modelName) {
    const folderPath = "Agent Chats";
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await this.app.vault.createFolder(folderPath);
    }
    const now = /* @__PURE__ */ new Date();
    const dateStr = now.toISOString().replace(/T/, " ").replace(/\..+/, "");
    const fileDateStr = now.toISOString().slice(0, 10) + "-" + now.toTimeString().slice(0, 5).replace(":", "-");
    const filename = `${folderPath}/Agent Chat ${fileDateStr}.md`;
    let mdContent = `---
tags:
  - agent-chat
created: ${dateStr}
model: ${modelName}
---

# Harness Bot Chat Session (${dateStr})

`;
    for (const msg of messages) {
      if (msg.role === "user") {
        mdContent += `### User
${msg.content}

`;
      } else if (msg.role === "assistant") {
        if (msg.content) {
          mdContent += `### Harness Bot
${msg.content}

`;
        }
        if (msg.tool_calls && msg.tool_calls.length > 0) {
          mdContent += `> **Tool Calls Requested:**
`;
          for (const tc of msg.tool_calls) {
            mdContent += `> - \`${tc.function.name}\` \`\`\`json
${tc.function.arguments}
\`\`\`
`;
          }
          mdContent += `
`;
        }
      } else if (msg.role === "tool") {
        mdContent += `> **Tool Result (${msg.name}):**
\`\`\`
${msg.content}
\`\`\`

`;
      }
    }
    const createdFile = await this.app.vault.create(filename, mdContent);
    return createdFile.path;
  }
};

// src/utils/session-manager.ts
var SessionManager = class {
  /**
   * Generates a clean human-readable session title from the user prompt.
   */
  static generateTitle(firstUserMessage) {
    const clean = firstUserMessage.replace(/[\n\r]+/g, " ").trim();
    if (clean.length === 0)
      return "New Chat Session";
    if (clean.length <= 40)
      return clean;
    const words = clean.split(" ");
    let result = "";
    for (const w of words) {
      if ((result + " " + w).trim().length > 35)
        break;
      result = (result + " " + w).trim();
    }
    return result ? `${result}...` : clean.slice(0, 35) + "...";
  }
  /**
   * Creates a new empty session object.
   */
  static createNewSession(providerId, model) {
    const id = `session_${Date.now()}`;
    return {
      id,
      title: "New Chat Session",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      messages: [],
      providerId,
      model
    };
  }
};

// src/utils/mention-helper.ts
var import_obsidian12 = require("obsidian");
var MentionHelper = class {
  /**
   * Returns all searchable files and folders in the Vault for @ autocomplete suggestions.
   */
  static getVaultItems(app, query = "") {
    const allFiles = app.vault.getAllLoadedFiles();
    const queryLower = query.toLowerCase();
    const items = [];
    for (const item of allFiles) {
      if (item.path === "/" || item.path === "")
        continue;
      const isFolder = item instanceof import_obsidian12.TFolder;
      if (!queryLower || item.name.toLowerCase().includes(queryLower) || item.path.toLowerCase().includes(queryLower)) {
        items.push({
          name: item.name,
          path: item.path,
          isFolder
        });
      }
    }
    return items.sort((a, b) => {
      if (a.isFolder && !b.isFolder)
        return -1;
      if (!a.isFolder && b.isFolder)
        return 1;
      return a.path.localeCompare(b.path);
    }).slice(0, 15);
  }
  /**
   * Scans a message for @references and attaches the real file/folder contents.
   */
  static async resolveMentions(app, userText) {
    const mentionRegex = /@([a-zA-Z0-9_\-\.\/]+)/g;
    const matches = Array.from(userText.matchAll(mentionRegex));
    if (matches.length === 0)
      return userText;
    let enrichedText = userText;
    const attachedBlocks = [];
    for (const match of matches) {
      const targetPath = match[1];
      const item = app.vault.getAbstractFileByPath(targetPath);
      if (item instanceof import_obsidian12.TFile) {
        try {
          const content = await app.vault.read(item);
          attachedBlocks.push(
            `[Attached Note: @${item.path}]
\`\`\`markdown
${content}
\`\`\``
          );
        } catch (e) {
        }
      } else if (item instanceof import_obsidian12.TFolder) {
        try {
          const children = item.children.map((c) => `- ${c.name} (${c instanceof import_obsidian12.TFolder ? "folder" : "file"})`).join("\n");
          attachedBlocks.push(
            `[Attached Folder: @${item.path}]
\`\`\`
${children}
\`\`\``
          );
        } catch (e) {
        }
      }
    }
    if (attachedBlocks.length > 0) {
      enrichedText = `${enrichedText}

${attachedBlocks.join("\n\n")}`;
    }
    return enrichedText;
  }
};

// src/ui/components/confirmation-modal.ts
var import_obsidian13 = require("obsidian");
var ConfirmationModal = class extends import_obsidian13.Modal {
  constructor(app, toolCall, onResult) {
    super(app);
    this.toolCall = toolCall;
    this.onResult = onResult;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("harness-modal-content");
    contentEl.createEl("h3", { text: "File Action Confirmation" });
    contentEl.createEl("p", {
      text: `The AI Agent is requesting permission to execute tool: "${this.toolCall.function.name}".`
    });
    const codeBlock = contentEl.createEl("pre");
    codeBlock.createEl("code", { text: this.toolCall.function.arguments });
    new import_obsidian13.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Deny").onClick(() => {
        this.onResult(false);
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Approve & Execute").setCta().onClick(() => {
        this.onResult(true);
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/components/sessions-modal.ts
var import_obsidian14 = require("obsidian");
var SessionsModal = class extends import_obsidian14.Modal {
  constructor(app, sessions, currentSessionId, onSelect, onDelete, onNewSession) {
    super(app);
    this.sessions = [...sessions];
    this.currentSessionId = currentSessionId;
    this.onSelect = onSelect;
    this.onDelete = onDelete;
    this.onNewSession = onNewSession;
  }
  onOpen() {
    this.render();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("harness-modal-content");
    contentEl.createEl("h2", { text: "Chat Sessions" });
    const topSetting = new import_obsidian14.Setting(contentEl).setName("New Conversation").setDesc("Start a fresh agent harness session");
    topSetting.addButton((btn) => {
      btn.setButtonText("+ New Session");
      btn.setCta();
      btn.onClick(() => {
        this.onNewSession();
        this.close();
      });
    });
    contentEl.createEl("h4", { text: "Previous Sessions" });
    const listEl = contentEl.createEl("div", { cls: "harness-sessions-list" });
    listEl.style.maxHeight = "320px";
    listEl.style.overflowY = "auto";
    listEl.style.display = "flex";
    listEl.style.flexDirection = "column";
    listEl.style.gap = "8px";
    listEl.style.marginBottom = "12px";
    if (this.sessions.length === 0) {
      listEl.createEl("div", { text: "No previous chat sessions found.", cls: "setting-item-description" });
      return;
    }
    const sorted = [...this.sessions].sort((a, b) => b.updatedAt - a.updatedAt);
    for (const session of sorted) {
      const isCurrent = session.id === this.currentSessionId;
      const sessionRow = listEl.createEl("div");
      sessionRow.style.display = "flex";
      sessionRow.style.alignItems = "center";
      sessionRow.style.justifyContent = "space-between";
      sessionRow.style.padding = "8px 10px";
      sessionRow.style.borderRadius = "6px";
      sessionRow.style.backgroundColor = isCurrent ? "var(--background-modifier-active-hover)" : "var(--background-secondary)";
      sessionRow.style.border = isCurrent ? "1px solid var(--interactive-accent)" : "1px solid var(--background-modifier-border)";
      const infoEl = sessionRow.createEl("div");
      infoEl.style.cursor = "pointer";
      infoEl.style.flex = "1";
      const titleEl = infoEl.createEl("div", { text: session.title, cls: "harness-session-title" });
      titleEl.style.fontWeight = "bold";
      titleEl.style.fontSize = "0.95em";
      const dateStr = new Date(session.updatedAt).toLocaleDateString() + " " + new Date(session.updatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
      const metaEl = infoEl.createEl("div", {
        text: `${dateStr} \u2022 ${session.messages.length} messages \u2022 ${session.model || "model"}`,
        cls: "setting-item-description"
      });
      metaEl.style.fontSize = "0.75em";
      infoEl.addEventListener("click", () => {
        this.onSelect(session.id);
        this.close();
      });
      const actionsEl = sessionRow.createEl("div");
      actionsEl.style.display = "flex";
      actionsEl.style.gap = "4px";
      const delBtn = actionsEl.createEl("button", { cls: "harness-btn-icon-round" });
      (0, import_obsidian14.setIcon)(delBtn, "trash");
      delBtn.setAttribute("aria-label", "Delete session");
      delBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.onDelete(session.id);
        this.sessions = this.sessions.filter((s) => s.id !== session.id);
        this.render();
      });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/ui/chat-view.ts
var HARNESS_VIEW_TYPE = "harness-chat-view";
var HarnessChatView = class extends import_obsidian15.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.isInputExpanded = false;
    this.activeSuggestType = "none";
    this.selectedSuggestIndex = 0;
    this.currentSuggestItems = [];
    this.currentAbortController = null;
    this.adjustForKeyboard = () => {
      const container = this.containerEl.children[1];
      if (!container)
        return;
      if (window.visualViewport) {
        const vv = window.visualViewport;
        const containerTop = container.getBoundingClientRect().top;
        const visibleHeight = vv.height - Math.max(0, containerTop);
        if (visibleHeight > 100) {
          container.style.height = `${visibleHeight}px`;
          container.style.maxHeight = `${visibleHeight}px`;
        }
      }
      if (this.messagesContainerEl) {
        this.messagesContainerEl.scrollTop = this.messagesContainerEl.scrollHeight;
      }
    };
    this.plugin = plugin;
    this.toolRegistry = new ToolRegistry();
    this.agentHarness = new AgentHarness(this.app, this.plugin.settings, this.toolRegistry);
    this.exporter = new MarkdownExporter(this.app);
    this.initSession();
  }
  initSession() {
    if (!this.plugin.settings.sessions) {
      this.plugin.settings.sessions = [];
    }
    const currentId = this.plugin.settings.currentSessionId;
    let existing = this.plugin.settings.sessions.find((s) => s.id === currentId);
    if (!existing) {
      existing = SessionManager.createNewSession(
        this.plugin.settings.activeProviderId || "openrouter",
        this.plugin.settings.activeModel || ""
      );
      this.plugin.settings.sessions.unshift(existing);
      this.plugin.settings.currentSessionId = existing.id;
    }
    this.currentSession = existing;
  }
  getViewType() {
    return HARNESS_VIEW_TYPE;
  }
  getDisplayText() {
    return "Harness Bot";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("harness-chat-container");
    const headerEl = container.createEl("div", { cls: "harness-chat-header" });
    const titleEl = headerEl.createEl("div", { cls: "harness-title-container" });
    titleEl.style.display = "flex";
    titleEl.style.alignItems = "center";
    titleEl.style.gap = "6px";
    const botIconEl = titleEl.createEl("span");
    (0, import_obsidian15.setIcon)(botIconEl, "bot");
    titleEl.createEl("span", { text: "Harness Bot", cls: "harness-title" });
    const headerActionsEl = headerEl.createEl("div", { cls: "harness-chat-header-actions" });
    const newSessionBtn = headerActionsEl.createEl("button", { cls: "clickable-icon" });
    newSessionBtn.setAttribute("aria-label", "New Session");
    (0, import_obsidian15.setIcon)(newSessionBtn, "plus");
    newSessionBtn.addEventListener("click", () => {
      this.createNewSession();
    });
    const sessionsBtn = headerActionsEl.createEl("button", { cls: "clickable-icon" });
    sessionsBtn.setAttribute("aria-label", "View Saved Sessions (/sessions)");
    (0, import_obsidian15.setIcon)(sessionsBtn, "history");
    sessionsBtn.addEventListener("click", () => {
      this.openSessionsModal();
    });
    const exportBtn = headerActionsEl.createEl("button", { cls: "clickable-icon" });
    exportBtn.setAttribute("aria-label", "Export Chat to Markdown");
    (0, import_obsidian15.setIcon)(exportBtn, "upload");
    exportBtn.addEventListener("click", async () => {
      if (this.currentSession.messages.length === 0) {
        new import_obsidian15.Notice("No chat history to export.");
        return;
      }
      try {
        const exportedPath = await this.exporter.exportChatToMarkdown(
          this.currentSession.messages,
          this.currentSession.model || this.plugin.settings.activeModel || "default"
        );
        new import_obsidian15.Notice(`Chat exported to ${exportedPath}`);
      } catch (e) {
        new import_obsidian15.Notice(`Export failed: ${e.message}`);
      }
    });
    const clearBtn = headerActionsEl.createEl("button", { cls: "clickable-icon" });
    clearBtn.setAttribute("aria-label", "Clear Messages in Session");
    (0, import_obsidian15.setIcon)(clearBtn, "trash");
    clearBtn.addEventListener("click", async () => {
      this.currentSession.messages = [];
      await this.saveSessionState();
      this.renderMessages();
    });
    this.messagesContainerEl = container.createEl("div", { cls: "harness-chat-messages" });
    this.inputAreaEl = container.createEl("div", { cls: "harness-chat-input-area" });
    this.suggestPopupEl = this.inputAreaEl.createEl("div", { cls: "harness-suggest-popup" });
    this.suggestPopupEl.style.display = "none";
    const textareaWrapperEl = this.inputAreaEl.createEl("div", { cls: "harness-textarea-wrapper" });
    this.inputTextAreaEl = textareaWrapperEl.createEl("textarea", {
      cls: "harness-chat-textarea",
      placeholder: "Ask Harness Bot... ('/' for commands, '@' for notes)"
    });
    this.expandBtnEl = textareaWrapperEl.createEl("button", { cls: "harness-expand-btn clickable-icon" });
    this.expandBtnEl.setAttribute("aria-label", "Expand to full view");
    this.expandBtnEl.style.display = "none";
    (0, import_obsidian15.setIcon)(this.expandBtnEl, "maximize-2");
    this.expandBtnEl.addEventListener("click", () => {
      this.toggleInputExpand();
    });
    const bottomRowEl = this.inputAreaEl.createEl("div", { cls: "harness-chat-bottom-row" });
    this.modelSelectEl = bottomRowEl.createEl("select", { cls: "harness-model-select" });
    this.refreshModelDropdown();
    this.modelSelectEl.addEventListener("change", async () => {
      this.currentSession.model = this.modelSelectEl.value;
      this.plugin.settings.activeModel = this.modelSelectEl.value;
      await this.saveSessionState();
    });
    this.sendButtonEl = bottomRowEl.createEl("button", { cls: "harness-send-btn mod-cta clickable-icon" });
    this.setSendButtonState(false);
    const handleSendOrStop = async () => {
      if (this.currentAbortController) {
        this.currentAbortController.abort();
        this.currentAbortController = null;
        this.setSendButtonState(false);
        new import_obsidian15.Notice("Generation stopped.");
        return;
      }
      const text = this.inputTextAreaEl.value.trim();
      if (!text)
        return;
      if (text === "/sessions" || text === "/history") {
        this.inputTextAreaEl.value = "";
        this.hideSuggest();
        this.resetTextareaHeight();
        this.openSessionsModal();
        return;
      } else if (text === "/new") {
        this.inputTextAreaEl.value = "";
        this.hideSuggest();
        this.resetTextareaHeight();
        this.createNewSession();
        return;
      } else if (text === "/clear") {
        this.inputTextAreaEl.value = "";
        this.hideSuggest();
        this.resetTextareaHeight();
        this.currentSession.messages = [];
        await this.saveSessionState();
        this.renderMessages();
        return;
      } else if (text === "/export") {
        this.inputTextAreaEl.value = "";
        this.hideSuggest();
        this.resetTextareaHeight();
        exportBtn.click();
        return;
      }
      const activeProv = this.plugin.settings.providers.find(
        (p) => p.id === this.plugin.settings.activeProviderId
      );
      if (!activeProv) {
        new import_obsidian15.Notice("Please configure and select an AI provider in Settings first.");
        return;
      }
      this.inputTextAreaEl.value = "";
      this.hideSuggest();
      this.resetTextareaHeight();
      if (this.isInputExpanded) {
        this.toggleInputExpand();
      }
      this.currentAbortController = new AbortController();
      this.setSendButtonState(true);
      if (this.currentSession.messages.length === 0) {
        this.currentSession.title = SessionManager.generateTitle(text);
      }
      const resolvedContent = await MentionHelper.resolveMentions(this.app, text);
      const userMsg = { role: "user", content: resolvedContent };
      this.currentSession.messages.push(userMsg);
      this.currentSession.updatedAt = Date.now();
      await this.saveSessionState();
      this.renderMessages();
      const streamingMsgEl = this.messagesContainerEl.createEl("div", {
        cls: "harness-message harness-message-assistant"
      });
      streamingMsgEl.createEl("div", {
        text: `Harness Bot (${this.currentSession.model || this.plugin.settings.activeModel})`,
        cls: "harness-message-header"
      });
      const textContentEl = streamingMsgEl.createEl("div", { cls: "harness-message-body" });
      try {
        const updatedHistory = await this.agentHarness.runTurn(
          this.currentSession.messages,
          (event) => {
            if (event.type === "chunk" && event.content) {
              textContentEl.setText(event.content);
              this.messagesContainerEl.scrollTop = this.messagesContainerEl.scrollHeight;
            } else if (event.type === "tool_call" && event.toolCall) {
              const card = this.messagesContainerEl.createEl("div", { cls: "harness-tool-card" });
              card.createEl("div", {
                text: `Tool requested: ${event.toolCall.function.name}`,
                cls: "harness-tool-title"
              });
            }
          },
          (toolCall) => {
            return new Promise((resolve) => {
              new ConfirmationModal(this.app, toolCall, resolve).open();
            });
          },
          this.plugin.settings.activeProviderId,
          this.currentSession.model || this.plugin.settings.activeModel,
          this.currentAbortController.signal
        );
        this.currentSession.messages = updatedHistory;
        this.currentSession.updatedAt = Date.now();
        await this.saveSessionState();
      } catch (err) {
        if (err.message && err.message.includes("stopped")) {
          textContentEl.setText(textContentEl.innerText + " [Stopped]");
        } else {
          new import_obsidian15.Notice(`Agent error: ${err.message}`);
          textContentEl.setText(`Error: ${err.message}`);
        }
      } finally {
        this.currentAbortController = null;
        this.setSendButtonState(false);
        this.renderMessages();
      }
    };
    this.sendButtonEl.addEventListener("click", handleSendOrStop);
    this.inputTextAreaEl.addEventListener("input", () => {
      this.autoResizeTextarea();
      this.handleInputSuggest();
    });
    this.inputTextAreaEl.addEventListener("focus", () => {
      setTimeout(this.adjustForKeyboard, 50);
      setTimeout(this.adjustForKeyboard, 250);
      setTimeout(this.adjustForKeyboard, 500);
    });
    this.inputTextAreaEl.addEventListener("blur", () => {
      setTimeout(this.adjustForKeyboard, 100);
    });
    this.inputTextAreaEl.addEventListener("keydown", (e) => {
      if (this.activeSuggestType !== "none") {
        if (e.key === "ArrowDown") {
          e.preventDefault();
          this.selectedSuggestIndex = (this.selectedSuggestIndex + 1) % Math.max(1, this.currentSuggestItems.length);
          this.highlightSuggestItem();
          return;
        } else if (e.key === "ArrowUp") {
          e.preventDefault();
          this.selectedSuggestIndex = (this.selectedSuggestIndex - 1 + this.currentSuggestItems.length) % Math.max(1, this.currentSuggestItems.length);
          this.highlightSuggestItem();
          return;
        } else if (e.key === "Enter" || e.key === "Tab") {
          if (this.currentSuggestItems[this.selectedSuggestIndex]) {
            e.preventDefault();
            this.currentSuggestItems[this.selectedSuggestIndex].onSelect();
            return;
          }
        } else if (e.key === "Escape") {
          this.hideSuggest();
          return;
        }
      }
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        handleSendOrStop();
      }
    });
    if (window.visualViewport) {
      window.visualViewport.addEventListener("resize", this.adjustForKeyboard);
      window.visualViewport.addEventListener("scroll", this.adjustForKeyboard);
    }
    this.adjustForKeyboard();
    this.renderMessages();
  }
  autoResizeTextarea() {
    if (this.isInputExpanded)
      return;
    this.inputTextAreaEl.style.height = "auto";
    const nextHeight = Math.min(160, Math.max(48, this.inputTextAreaEl.scrollHeight));
    this.inputTextAreaEl.style.height = `${nextHeight}px`;
    const lineCount = this.inputTextAreaEl.value.split("\n").length;
    const isLong = lineCount >= 4 || this.inputTextAreaEl.scrollHeight > 85;
    this.expandBtnEl.style.display = isLong ? "flex" : "none";
  }
  resetTextareaHeight() {
    if (this.isInputExpanded)
      return;
    this.inputTextAreaEl.style.height = "48px";
    this.expandBtnEl.style.display = "none";
  }
  toggleInputExpand() {
    this.isInputExpanded = !this.isInputExpanded;
    if (this.isInputExpanded) {
      this.inputAreaEl.addClass("is-expanded");
      (0, import_obsidian15.setIcon)(this.expandBtnEl, "minimize-2");
      this.expandBtnEl.setAttribute("aria-label", "Collapse view");
      this.expandBtnEl.style.display = "flex";
      this.adjustForKeyboard();
      this.inputTextAreaEl.focus();
    } else {
      this.inputAreaEl.removeClass("is-expanded");
      (0, import_obsidian15.setIcon)(this.expandBtnEl, "maximize-2");
      this.expandBtnEl.setAttribute("aria-label", "Expand to full view");
      this.autoResizeTextarea();
      this.adjustForKeyboard();
      this.inputTextAreaEl.focus();
    }
  }
  setSendButtonState(isGenerating) {
    if (!this.sendButtonEl)
      return;
    this.sendButtonEl.empty();
    if (isGenerating) {
      (0, import_obsidian15.setIcon)(this.sendButtonEl, "square");
      this.sendButtonEl.addClass("mod-warning");
      this.sendButtonEl.removeClass("mod-cta");
      this.sendButtonEl.setAttribute("aria-label", "Stop generation");
    } else {
      (0, import_obsidian15.setIcon)(this.sendButtonEl, "send");
      this.sendButtonEl.addClass("mod-cta");
      this.sendButtonEl.removeClass("mod-warning");
      this.sendButtonEl.setAttribute("aria-label", "Send message");
    }
  }
  handleInputSuggest() {
    const text = this.inputTextAreaEl.value;
    const cursorPos = this.inputTextAreaEl.selectionStart || text.length;
    const beforeCursor = text.slice(0, cursorPos);
    const slashMatch = beforeCursor.match(/\/([a-zA-Z0-9_-]*)$/);
    if (slashMatch) {
      this.activeSuggestType = "slash";
      const query = slashMatch[1].toLowerCase();
      this.renderSlashSuggest(query, slashMatch.index || 0);
      return;
    }
    const atMatch = beforeCursor.match(/@([a-zA-Z0-9_\-\.\/]*)$/);
    if (atMatch) {
      this.activeSuggestType = "mention";
      const query = atMatch[1];
      this.renderMentionSuggest(query, atMatch.index || 0);
      return;
    }
    this.hideSuggest();
  }
  renderSlashSuggest(query, matchIndex) {
    if (!this.suggestPopupEl)
      return;
    this.suggestPopupEl.empty();
    this.currentSuggestItems = [];
    this.selectedSuggestIndex = 0;
    const commands = [
      {
        cmd: "/sessions",
        desc: "View & switch saved chat sessions",
        action: () => {
          this.inputTextAreaEl.value = "";
          this.hideSuggest();
          this.resetTextareaHeight();
          this.openSessionsModal();
        }
      },
      {
        cmd: "/new",
        desc: "Start a new conversation session",
        action: () => {
          this.inputTextAreaEl.value = "";
          this.hideSuggest();
          this.resetTextareaHeight();
          this.createNewSession();
        }
      },
      {
        cmd: "/clear",
        desc: "Clear messages in current session",
        action: () => {
          this.inputTextAreaEl.value = "";
          this.hideSuggest();
          this.resetTextareaHeight();
          this.currentSession.messages = [];
          this.saveSessionState();
          this.renderMessages();
        }
      },
      {
        cmd: "/export",
        desc: "Export chat to Markdown note",
        action: () => {
          this.inputTextAreaEl.value = "";
          this.hideSuggest();
          this.resetTextareaHeight();
          this.exporter.exportChatToMarkdown(
            this.currentSession.messages,
            this.currentSession.model || this.plugin.settings.activeModel || "default"
          );
        }
      }
    ];
    const filtered = commands.filter((c) => c.cmd.toLowerCase().includes(query) || c.desc.toLowerCase().includes(query));
    if (filtered.length === 0) {
      this.hideSuggest();
      return;
    }
    this.suggestPopupEl.style.display = "flex";
    filtered.forEach((item, index) => {
      const onSelect = () => item.action();
      this.currentSuggestItems.push({ label: item.cmd, onSelect });
      const itemEl = this.suggestPopupEl.createEl("div", { cls: "harness-suggest-item" });
      if (index === 0)
        itemEl.addClass("is-selected");
      itemEl.createEl("strong", { text: item.cmd });
      itemEl.createEl("span", { text: ` - ${item.desc}` });
      itemEl.addEventListener("click", onSelect);
    });
  }
  renderMentionSuggest(query, matchIndex) {
    if (!this.suggestPopupEl)
      return;
    this.suggestPopupEl.empty();
    this.currentSuggestItems = [];
    this.selectedSuggestIndex = 0;
    const items = MentionHelper.getVaultItems(this.app, query);
    if (items.length === 0) {
      this.hideSuggest();
      return;
    }
    this.suggestPopupEl.style.display = "flex";
    items.forEach((item, index) => {
      const onSelect = () => {
        const text = this.inputTextAreaEl.value;
        const before = text.slice(0, matchIndex);
        const after = text.slice(matchIndex + 1 + query.length);
        this.inputTextAreaEl.value = `${before}@${item.path} ${after}`;
        this.hideSuggest();
        this.autoResizeTextarea();
        this.inputTextAreaEl.focus();
      };
      this.currentSuggestItems.push({ label: item.path, onSelect });
      const itemEl = this.suggestPopupEl.createEl("div", { cls: "harness-suggest-item" });
      if (index === 0)
        itemEl.addClass("is-selected");
      const iconSpan = itemEl.createEl("span", { cls: "harness-suggest-icon" });
      (0, import_obsidian15.setIcon)(iconSpan, item.isFolder ? "folder" : "file-text");
      itemEl.createEl("span", { text: ` ${item.path}` });
      itemEl.addEventListener("click", onSelect);
    });
  }
  highlightSuggestItem() {
    if (!this.suggestPopupEl)
      return;
    const itemEls = this.suggestPopupEl.querySelectorAll(".harness-suggest-item");
    itemEls.forEach((el, idx) => {
      if (idx === this.selectedSuggestIndex) {
        el.addClass("is-selected");
        el.scrollIntoView({ block: "nearest" });
      } else {
        el.removeClass("is-selected");
      }
    });
  }
  hideSuggest() {
    this.activeSuggestType = "none";
    this.currentSuggestItems = [];
    if (this.suggestPopupEl) {
      this.suggestPopupEl.style.display = "none";
      this.suggestPopupEl.empty();
    }
  }
  createNewSession() {
    const newSession = SessionManager.createNewSession(
      this.plugin.settings.activeProviderId || "openrouter",
      this.plugin.settings.activeModel || ""
    );
    this.plugin.settings.sessions.unshift(newSession);
    this.plugin.settings.currentSessionId = newSession.id;
    this.currentSession = newSession;
    this.saveSessionState();
    this.renderMessages();
    this.refreshModelDropdown();
    new import_obsidian15.Notice("Started new chat session");
  }
  openSessionsModal() {
    new SessionsModal(
      this.app,
      this.plugin.settings.sessions,
      this.currentSession.id,
      (selectedId) => {
        const found = this.plugin.settings.sessions.find((s) => s.id === selectedId);
        if (found) {
          this.currentSession = found;
          this.plugin.settings.currentSessionId = found.id;
          this.saveSessionState();
          this.renderMessages();
          this.refreshModelDropdown();
        }
      },
      (deletedId) => {
        this.plugin.settings.sessions = this.plugin.settings.sessions.filter((s) => s.id !== deletedId);
        if (this.currentSession.id === deletedId) {
          this.createNewSession();
        } else {
          this.saveSessionState();
        }
      },
      () => {
        this.createNewSession();
      }
    ).open();
  }
  async saveSessionState() {
    const idx = this.plugin.settings.sessions.findIndex((s) => s.id === this.currentSession.id);
    if (idx !== -1) {
      this.plugin.settings.sessions[idx] = this.currentSession;
    } else {
      this.plugin.settings.sessions.unshift(this.currentSession);
    }
    this.plugin.settings.currentSessionId = this.currentSession.id;
    await this.plugin.saveSettings();
  }
  refreshModelDropdown() {
    if (!this.modelSelectEl)
      return;
    this.modelSelectEl.empty();
    const activeProv = this.plugin.settings.providers.find(
      (p) => p.id === this.plugin.settings.activeProviderId
    );
    const models = activeProv?.models || [];
    if (models.length === 0) {
      this.modelSelectEl.createEl("option", { value: "", text: "(No models)" });
      return;
    }
    const selectedModel = this.currentSession.model || this.plugin.settings.activeModel || models[0];
    for (const m of models) {
      const opt = this.modelSelectEl.createEl("option", { value: m, text: m });
      if (m === selectedModel)
        opt.selected = true;
    }
    if (!models.includes(selectedModel)) {
      this.currentSession.model = models[0];
      this.plugin.settings.activeModel = models[0];
    } else {
      this.currentSession.model = selectedModel;
      this.plugin.settings.activeModel = selectedModel;
    }
  }
  renderMessages() {
    if (!this.messagesContainerEl)
      return;
    this.messagesContainerEl.empty();
    if (this.currentSession.messages.length === 0) {
      const previousSessions = this.plugin.settings.sessions.filter(
        (s) => s.id !== this.currentSession.id && s.messages.length > 0
      );
      if (previousSessions.length > 0) {
        const emptyContainerEl = this.messagesContainerEl.createEl("div", {
          cls: "harness-empty-state-container"
        });
        const prevBoxEl = emptyContainerEl.createEl("div", { cls: "harness-prev-sessions-box" });
        prevBoxEl.style.width = "100%";
        prevBoxEl.style.maxWidth = "360px";
        prevBoxEl.style.border = "1px solid var(--background-modifier-border)";
        prevBoxEl.style.borderRadius = "8px";
        prevBoxEl.style.padding = "12px";
        prevBoxEl.style.backgroundColor = "var(--background-secondary)";
        prevBoxEl.createEl("h4", { text: "Previous Sessions" });
        const prevListEl = prevBoxEl.createEl("div");
        prevListEl.style.display = "flex";
        prevListEl.style.flexDirection = "column";
        prevListEl.style.gap = "6px";
        for (const prev of previousSessions.slice(0, 5)) {
          const itemBtn = prevListEl.createEl("div", { cls: "harness-session-card" });
          itemBtn.style.padding = "8px 10px";
          itemBtn.style.borderRadius = "6px";
          itemBtn.style.cursor = "pointer";
          itemBtn.style.backgroundColor = "var(--background-primary)";
          itemBtn.style.border = "1px solid var(--background-modifier-border)";
          const titleRow = itemBtn.createEl("div", { text: prev.title });
          titleRow.style.fontWeight = "bold";
          titleRow.style.fontSize = "0.9em";
          const dateStr = new Date(prev.updatedAt).toLocaleDateString();
          itemBtn.createEl("div", {
            text: `${dateStr} \u2022 ${prev.messages.length} messages`,
            cls: "setting-item-description"
          });
          itemBtn.addEventListener("click", () => {
            this.currentSession = prev;
            this.plugin.settings.currentSessionId = prev.id;
            this.saveSessionState();
            this.renderMessages();
            this.refreshModelDropdown();
          });
        }
      }
      return;
    }
    for (const msg of this.currentSession.messages) {
      if (msg.role === "user") {
        const msgEl = this.messagesContainerEl.createEl("div", { cls: "harness-message harness-message-user" });
        msgEl.createEl("div", { text: "You", cls: "harness-message-header" });
        msgEl.createEl("div", {
          text: typeof msg.content === "string" ? msg.content : JSON.stringify(msg.content || ""),
          cls: "harness-message-body"
        });
      } else if (msg.role === "assistant") {
        if (msg.content) {
          const msgEl = this.messagesContainerEl.createEl("div", { cls: "harness-message harness-message-assistant" });
          msgEl.createEl("div", { text: "Harness Bot", cls: "harness-message-header" });
          msgEl.createEl("div", {
            text: typeof msg.content === "string" ? msg.content : JSON.stringify(msg.content || ""),
            cls: "harness-message-body"
          });
        }
        if (msg.tool_calls) {
          for (const tc of msg.tool_calls) {
            const card = this.messagesContainerEl.createEl("div", { cls: "harness-tool-card" });
            card.createEl("div", { text: `Tool: ${tc.function.name}`, cls: "harness-tool-title" });
            const argsPre = card.createEl("pre");
            argsPre.createEl("code", { text: tc.function.arguments });
          }
        }
      } else if (msg.role === "tool") {
        const card = this.messagesContainerEl.createEl("div", { cls: "harness-tool-card" });
        card.createEl("div", { text: `Tool Output (${msg.name})`, cls: "harness-tool-title" });
        const outPre = card.createEl("pre");
        outPre.createEl("code", {
          text: typeof msg.content === "string" ? msg.content : JSON.stringify(msg.content || "")
        });
      }
    }
    this.messagesContainerEl.scrollTop = this.messagesContainerEl.scrollHeight;
  }
  async onClose() {
    if (this.currentAbortController) {
      this.currentAbortController.abort();
    }
    if (window.visualViewport) {
      window.visualViewport.removeEventListener("resize", this.adjustForKeyboard);
      window.visualViewport.removeEventListener("scroll", this.adjustForKeyboard);
    }
  }
};

// src/main.ts
var HarnessPlugin = class extends import_obsidian16.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(HARNESS_VIEW_TYPE, (leaf) => new HarnessChatView(leaf, this));
    this.addRibbonIcon("bot", "Open Obsidian Harness Bot", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-obsidian-harness-bot",
      name: "Open Obsidian Harness Bot",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new HarnessSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(HARNESS_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: HARNESS_VIEW_TYPE,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (!this.settings.providers || this.settings.providers.length === 0) {
      this.settings.providers = DEFAULT_SETTINGS.providers;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
