/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HarnessPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian11 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  openRouterSecretName: "openrouter-api-key",
  openAiSecretName: "openai-api-key",
  anthropicSecretName: "anthropic-api-key",
  defaultProvider: "openrouter",
  defaultModel: "anthropic/claude-3.7-sonnet",
  customBaseUrl: "http://localhost:11434/v1",
  systemPrompt: "You are an autonomous AI Agent inside Obsidian. You have tools to read, create, patch, search, and inspect notes in the vault. Use these tools step-by-step to fulfill the user request.",
  safetyMode: "strict",
  maxAgentSteps: 10
};

// src/ui/settings-tab.ts
var import_obsidian = require("obsidian");
var HarnessSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Obsidian Agent Harness Settings" });
    new import_obsidian.Setting(containerEl).setName("OpenRouter Secret Name").setDesc("Select or create a secret for OpenRouter API Key using Obsidian SecretStorage").addComponent((el) => {
      try {
        return new import_obsidian.SecretComponent(this.app, el).setValue(this.plugin.settings.openRouterSecretName).onChange(async (value) => {
          this.plugin.settings.openRouterSecretName = value;
          await this.plugin.saveSettings();
        });
      } catch (e) {
        const textInput = el.createEl("input", { type: "password", value: this.plugin.settings.openRouterSecretName });
        textInput.addEventListener("change", async (ev) => {
          this.plugin.settings.openRouterSecretName = ev.target.value;
          await this.plugin.saveSettings();
        });
        return el;
      }
    });
    new import_obsidian.Setting(containerEl).setName("OpenAI Secret Name").setDesc("Select or create a secret for OpenAI API Key").addComponent((el) => {
      try {
        return new import_obsidian.SecretComponent(this.app, el).setValue(this.plugin.settings.openAiSecretName).onChange(async (value) => {
          this.plugin.settings.openAiSecretName = value;
          await this.plugin.saveSettings();
        });
      } catch (e) {
        const textInput = el.createEl("input", { type: "password", value: this.plugin.settings.openAiSecretName });
        textInput.addEventListener("change", async (ev) => {
          this.plugin.settings.openAiSecretName = ev.target.value;
          await this.plugin.saveSettings();
        });
        return el;
      }
    });
    new import_obsidian.Setting(containerEl).setName("Anthropic Secret Name").setDesc("Select or create a secret for Anthropic API Key").addComponent((el) => {
      try {
        return new import_obsidian.SecretComponent(this.app, el).setValue(this.plugin.settings.anthropicSecretName).onChange(async (value) => {
          this.plugin.settings.anthropicSecretName = value;
          await this.plugin.saveSettings();
        });
      } catch (e) {
        const textInput = el.createEl("input", { type: "password", value: this.plugin.settings.anthropicSecretName });
        textInput.addEventListener("change", async (ev) => {
          this.plugin.settings.anthropicSecretName = ev.target.value;
          await this.plugin.saveSettings();
        });
        return el;
      }
    });
    new import_obsidian.Setting(containerEl).setName("Default Provider").setDesc("Select default LLM Provider").addDropdown(
      (dropdown) => dropdown.addOption("openrouter", "OpenRouter").addOption("openai", "OpenAI").addOption("anthropic", "Anthropic").addOption("ollama", "Ollama / Custom OpenAI-Compatible").setValue(this.plugin.settings.defaultProvider).onChange(async (value) => {
        this.plugin.settings.defaultProvider = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default Model ID").setDesc("Model identifier (e.g. anthropic/claude-3.7-sonnet, gpt-4o, llama3)").addText(
      (text) => text.setPlaceholder("anthropic/claude-3.7-sonnet").setValue(this.plugin.settings.defaultModel).onChange(async (value) => {
        this.plugin.settings.defaultModel = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Custom Base URL (Ollama / Local Server)").setDesc("Endpoint URL for Ollama or OpenAI-compatible custom servers").addText(
      (text) => text.setPlaceholder("http://localhost:11434/v1").setValue(this.plugin.settings.customBaseUrl).onChange(async (value) => {
        this.plugin.settings.customBaseUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Vault Modification Safety Mode").setDesc("Strict mode prompts for user confirmation before writing or modifying any Vault file").addDropdown(
      (dropdown) => dropdown.addOption("strict", "Strict (Prompt before file edits)").addOption("auto", "Auto (Auto-approve file edits)").setValue(this.plugin.settings.safetyMode).onChange(async (value) => {
        this.plugin.settings.safetyMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max Agent Iterations").setDesc("Maximum tool-execution steps per turn (1 to 25)").addSlider(
      (slider) => slider.setLimits(1, 25, 1).setValue(this.plugin.settings.maxAgentSteps).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxAgentSteps = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("System Prompt").setDesc("Base instructions for the Agent Harness").addTextArea(
      (text) => text.setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/ui/chat-view.ts
var import_obsidian10 = require("obsidian");

// src/engine/providers/base.ts
var LLMProvider = class {
};

// src/utils/cache-helpers.ts
function sortToolSchemasDeterministically(tools) {
  return [...tools].sort((a, b) => a.name.localeCompare(b.name)).map((tool) => {
    const properties = tool.parameters.properties;
    const sortedPropertyKeys = Object.keys(properties).sort();
    const sortedProperties = {};
    for (const key of sortedPropertyKeys) {
      sortedProperties[key] = properties[key];
    }
    return {
      ...tool,
      parameters: {
        ...tool.parameters,
        properties: sortedProperties,
        required: tool.parameters.required ? [...tool.parameters.required].sort() : void 0
      }
    };
  });
}
function prepareNetworkPayloadMessages(messages) {
  if (messages.length === 0)
    return [];
  const networkMessages = JSON.parse(JSON.stringify(messages));
  for (let i = networkMessages.length - 1; i >= 0; i--) {
    if (networkMessages[i].role === "user" && typeof networkMessages[i].content === "string") {
      const nowIso = (/* @__PURE__ */ new Date()).toISOString();
      networkMessages[i].content = `${networkMessages[i].content}

[Current Date & Time: ${nowIso}]`;
      break;
    }
  }
  return networkMessages;
}

// src/engine/stream-parser.ts
var SSEStreamParser = class {
  constructor() {
    this.buffer = "";
  }
  /**
   * Processes a chunk of string text and extracts completed SSE event lines.
   */
  feed(chunk) {
    this.buffer += chunk;
    const events = [];
    const lines = this.buffer.split("\n");
    this.buffer = lines.pop() || "";
    let currentEvent = {};
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) {
        if (currentEvent.data !== void 0) {
          events.push(currentEvent);
          currentEvent = {};
        }
        continue;
      }
      if (trimmed.startsWith("event:")) {
        currentEvent.event = trimmed.substring(6).trim();
      } else if (trimmed.startsWith("data:")) {
        const dataPart = trimmed.substring(5).trim();
        if (currentEvent.data) {
          currentEvent.data += "\n" + dataPart;
        } else {
          currentEvent.data = dataPart;
        }
      }
    }
    return events;
  }
};

// src/engine/providers/openrouter.ts
var import_obsidian2 = require("obsidian");
var OpenRouterProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "openrouter";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk) {
    const endpoint = (baseUrl || "https://openrouter.ai/api/v1").replace(/\/$/, "") + "/chat/completions";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = [
      { role: "system", content: systemPrompt },
      ...networkMessages
    ];
    const formattedTools = sortedTools.map((t) => ({
      type: "function",
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }));
    const payload = {
      model: model || "anthropic/claude-3.7-sonnet",
      messages: formattedMessages,
      stream: true
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`,
          "HTTP-Referer": "https://github.com/killery/obsidian-harness-bot",
          "X-Title": "Obsidian Agent Harness"
        },
        body: JSON.stringify(payload)
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`OpenRouter HTTP ${response.status}: ${errorText}`);
      }
      const reader = response.body?.getReader();
      const decoder = new TextDecoder("utf-8");
      const parser = new SSEStreamParser();
      let fullContent = "";
      const toolCallMap = {};
      if (reader) {
        while (true) {
          const { done, value } = await reader.read();
          if (done)
            break;
          const text = decoder.decode(value, { stream: true });
          const events = parser.feed(text);
          for (const ev of events) {
            if (ev.data === "[DONE]")
              continue;
            try {
              const parsed = JSON.parse(ev.data);
              const delta = parsed.choices?.[0]?.delta;
              if (delta?.content) {
                fullContent += delta.content;
                if (onChunk)
                  onChunk(delta.content);
              }
              if (delta?.tool_calls) {
                for (const tc of delta.tool_calls) {
                  const idx = tc.index ?? 0;
                  if (!toolCallMap[idx]) {
                    toolCallMap[idx] = { id: tc.id || "", name: tc.function?.name || "", args: "" };
                  }
                  if (tc.id)
                    toolCallMap[idx].id = tc.id;
                  if (tc.function?.name)
                    toolCallMap[idx].name = tc.function.name;
                  if (tc.function?.arguments)
                    toolCallMap[idx].args += tc.function.arguments;
                }
              }
            } catch (e) {
            }
          }
        }
      }
      const finalToolCalls = Object.values(toolCallMap).map((tc) => ({
        id: tc.id,
        type: "function",
        function: {
          name: tc.name,
          arguments: tc.args
        }
      }));
      return {
        content: fullContent,
        toolCalls: finalToolCalls.length > 0 ? finalToolCalls : void 0
      };
    } catch (err) {
      const reqRes = await (0, import_obsidian2.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({ ...payload, stream: false })
      });
      const resJson = reqRes.json;
      const choice = resJson.choices?.[0]?.message;
      return {
        content: choice?.content || "",
        toolCalls: choice?.tool_calls
      };
    }
  }
};

// src/engine/providers/openai.ts
var import_obsidian3 = require("obsidian");
var OpenAIProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "openai";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk) {
    const endpoint = (baseUrl || "https://api.openai.com/v1").replace(/\/$/, "") + "/chat/completions";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = [
      { role: "system", content: systemPrompt },
      ...networkMessages
    ];
    const formattedTools = sortedTools.map((t) => ({
      type: "function",
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }));
    const payload = {
      model: model || "gpt-4o",
      messages: formattedMessages,
      stream: true
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify(payload)
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`OpenAI HTTP ${response.status}: ${errorText}`);
      }
      const reader = response.body?.getReader();
      const decoder = new TextDecoder("utf-8");
      const parser = new SSEStreamParser();
      let fullContent = "";
      const toolCallMap = {};
      if (reader) {
        while (true) {
          const { done, value } = await reader.read();
          if (done)
            break;
          const text = decoder.decode(value, { stream: true });
          const events = parser.feed(text);
          for (const ev of events) {
            if (ev.data === "[DONE]")
              continue;
            try {
              const parsed = JSON.parse(ev.data);
              const delta = parsed.choices?.[0]?.delta;
              if (delta?.content) {
                fullContent += delta.content;
                if (onChunk)
                  onChunk(delta.content);
              }
              if (delta?.tool_calls) {
                for (const tc of delta.tool_calls) {
                  const idx = tc.index ?? 0;
                  if (!toolCallMap[idx]) {
                    toolCallMap[idx] = { id: tc.id || "", name: tc.function?.name || "", args: "" };
                  }
                  if (tc.id)
                    toolCallMap[idx].id = tc.id;
                  if (tc.function?.name)
                    toolCallMap[idx].name = tc.function.name;
                  if (tc.function?.arguments)
                    toolCallMap[idx].args += tc.function.arguments;
                }
              }
            } catch (e) {
            }
          }
        }
      }
      const finalToolCalls = Object.values(toolCallMap).map((tc) => ({
        id: tc.id,
        type: "function",
        function: {
          name: tc.name,
          arguments: tc.args
        }
      }));
      return {
        content: fullContent,
        toolCalls: finalToolCalls.length > 0 ? finalToolCalls : void 0
      };
    } catch (err) {
      const reqRes = await (0, import_obsidian3.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({ ...payload, stream: false })
      });
      const resJson = reqRes.json;
      const choice = resJson.choices?.[0]?.message;
      return {
        content: choice?.content || "",
        toolCalls: choice?.tool_calls
      };
    }
  }
};

// src/engine/providers/anthropic.ts
var import_obsidian4 = require("obsidian");
var AnthropicProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "anthropic";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk) {
    const endpoint = (baseUrl || "https://api.anthropic.com/v1").replace(/\/$/, "") + "/messages";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = networkMessages.map((msg) => ({
      role: msg.role === "assistant" ? "assistant" : "user",
      content: msg.content
    }));
    const formattedTools = sortedTools.map((t) => ({
      name: t.name,
      description: t.description,
      input_schema: t.parameters
    }));
    const payload = {
      model: model || "claude-3-7-sonnet-20250219",
      max_tokens: 4096,
      system: [
        {
          type: "text",
          text: systemPrompt,
          cache_control: { type: "ephemeral" }
        }
      ],
      messages: formattedMessages,
      stream: true
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01",
          "anthropic-beta": "prompt-caching-2024-07-31"
        },
        body: JSON.stringify(payload)
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Anthropic HTTP ${response.status}: ${errorText}`);
      }
      const reader = response.body?.getReader();
      const decoder = new TextDecoder("utf-8");
      const parser = new SSEStreamParser();
      let fullContent = "";
      const toolCallList = [];
      let currentToolCall = null;
      if (reader) {
        while (true) {
          const { done, value } = await reader.read();
          if (done)
            break;
          const text = decoder.decode(value, { stream: true });
          const events = parser.feed(text);
          for (const ev of events) {
            try {
              const parsed = JSON.parse(ev.data);
              if (parsed.type === "content_block_delta") {
                if (parsed.delta?.type === "text_delta") {
                  const chunk = parsed.delta.text;
                  fullContent += chunk;
                  if (onChunk)
                    onChunk(chunk);
                } else if (parsed.delta?.type === "input_json_delta") {
                  if (currentToolCall) {
                    currentToolCall.argsStr += parsed.delta.partial_json;
                  }
                }
              } else if (parsed.type === "content_block_start") {
                if (parsed.content_block?.type === "tool_use") {
                  currentToolCall = {
                    id: parsed.content_block.id,
                    name: parsed.content_block.name,
                    argsStr: ""
                  };
                }
              } else if (parsed.type === "content_block_stop") {
                if (currentToolCall) {
                  toolCallList.push({
                    id: currentToolCall.id,
                    type: "function",
                    function: {
                      name: currentToolCall.name,
                      arguments: currentToolCall.argsStr
                    }
                  });
                  currentToolCall = null;
                }
              }
            } catch (e) {
            }
          }
        }
      }
      return {
        content: fullContent,
        toolCalls: toolCallList.length > 0 ? toolCallList : void 0
      };
    } catch (err) {
      const reqRes = await (0, import_obsidian4.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify({ ...payload, stream: false })
      });
      const resJson = reqRes.json;
      let textContent = "";
      const toolCalls = [];
      for (const block of resJson.content || []) {
        if (block.type === "text") {
          textContent += block.text;
        } else if (block.type === "tool_use") {
          toolCalls.push({
            id: block.id,
            type: "function",
            function: {
              name: block.name,
              arguments: JSON.stringify(block.input)
            }
          });
        }
      }
      return {
        content: textContent,
        toolCalls: toolCalls.length > 0 ? toolCalls : void 0
      };
    }
  }
};

// src/engine/providers/ollama.ts
var import_obsidian5 = require("obsidian");
var OllamaProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "ollama";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk) {
    const endpoint = (baseUrl || "http://localhost:11434/v1").replace(/\/$/, "") + "/chat/completions";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = [
      { role: "system", content: systemPrompt },
      ...networkMessages
    ];
    const formattedTools = sortedTools.map((t) => ({
      type: "function",
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }));
    const payload = {
      model: model || "llama3",
      messages: formattedMessages,
      stream: false
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    const headers = {
      "Content-Type": "application/json"
    };
    if (apiKey) {
      headers["Authorization"] = `Bearer ${apiKey}`;
    }
    const reqRes = await (0, import_obsidian5.requestUrl)({
      url: endpoint,
      method: "POST",
      headers,
      body: JSON.stringify(payload)
    });
    const resJson = reqRes.json;
    const choice = resJson.choices?.[0]?.message;
    if (choice?.content && onChunk) {
      onChunk(choice.content);
    }
    const toolCalls = (choice?.tool_calls || []).map((tc) => ({
      id: tc.id || `call_${Date.now()}`,
      type: "function",
      function: {
        name: tc.function?.name || "",
        arguments: typeof tc.function?.arguments === "string" ? tc.function.arguments : JSON.stringify(tc.function?.arguments || {})
      }
    }));
    return {
      content: choice?.content || "",
      toolCalls: toolCalls.length > 0 ? toolCalls : void 0
    };
  }
};

// src/utils/secrets.ts
var SecretManager = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Retrieves the secret value associated with the given secret name using SecretStorage API.
   */
  getSecret(secretName) {
    if (!secretName) {
      return null;
    }
    const secretStorage = this.app.secretStorage;
    if (secretStorage && typeof secretStorage.getSecret === "function") {
      const secret = secretStorage.getSecret(secretName);
      return secret || null;
    }
    return null;
  }
};

// src/engine/agent.ts
var AgentHarness = class {
  constructor(app, settings, toolRegistry) {
    this.providers = /* @__PURE__ */ new Map();
    this.app = app;
    this.settings = settings;
    this.secretManager = new SecretManager(app);
    this.toolRegistry = toolRegistry;
    this.providers.set("openrouter", new OpenRouterProvider());
    this.providers.set("openai", new OpenAIProvider());
    this.providers.set("anthropic", new AnthropicProvider());
    this.providers.set("ollama", new OllamaProvider());
  }
  getActiveProvider() {
    const providerType = this.settings.defaultProvider || "openrouter";
    const provider = this.providers.get(providerType);
    if (!provider) {
      throw new Error(`Unsupported provider type: ${providerType}`);
    }
    let secretName = "";
    if (providerType === "openrouter")
      secretName = this.settings.openRouterSecretName;
    else if (providerType === "openai")
      secretName = this.settings.openAiSecretName;
    else if (providerType === "anthropic")
      secretName = this.settings.anthropicSecretName;
    const apiKey = secretName ? this.secretManager.getSecret(secretName) || "" : "";
    if (providerType !== "ollama" && !apiKey) {
      throw new Error(`No API key found for secret "${secretName}". Please set it in plugin settings using SecretStorage.`);
    }
    return { provider, apiKey };
  }
  /**
   * Runs the multi-step agent turn loop.
   */
  async runTurn(history, onEvent, onConfirm) {
    const { provider, apiKey } = this.getActiveProvider();
    const messages = [...history];
    const tools = this.toolRegistry.getSchemas();
    const maxSteps = this.settings.maxAgentSteps || 10;
    let step = 0;
    let keepRunning = true;
    while (keepRunning && step < maxSteps) {
      step++;
      let streamContent = "";
      const response = await provider.chatCompletion(
        apiKey,
        this.settings.customBaseUrl,
        this.settings.defaultModel,
        this.settings.systemPrompt,
        messages,
        tools,
        (chunk) => {
          streamContent += chunk;
          onEvent({
            type: "chunk",
            step,
            content: streamContent
          });
        }
      );
      const assistantMessage = {
        role: "assistant",
        content: response.content || "",
        tool_calls: response.toolCalls
      };
      messages.push(assistantMessage);
      if (response.toolCalls && response.toolCalls.length > 0) {
        for (const toolCall of response.toolCalls) {
          onEvent({
            type: "tool_call",
            step,
            toolCall
          });
          const toolInstance = this.toolRegistry.getTool(toolCall.function.name);
          if (toolInstance?.isMutation && this.settings.safetyMode === "strict") {
            onEvent({
              type: "awaiting_confirmation",
              step,
              toolCall
            });
            if (onConfirm) {
              const approved = await onConfirm(toolCall);
              if (!approved) {
                const cancelledResult = {
                  success: false,
                  output: "",
                  error: "User denied file modification permission for this tool execution."
                };
                messages.push({
                  role: "tool",
                  tool_call_id: toolCall.id,
                  name: toolCall.function.name,
                  content: JSON.stringify(cancelledResult)
                });
                onEvent({
                  type: "tool_result",
                  step,
                  toolResult: { toolCallId: toolCall.id, result: cancelledResult }
                });
                continue;
              }
            }
          }
          let parsedArgs = {};
          try {
            parsedArgs = JSON.parse(toolCall.function.arguments || "{}");
          } catch (e) {
            parsedArgs = {};
          }
          const result = await this.toolRegistry.executeTool(toolCall.function.name, parsedArgs, this.app);
          messages.push({
            role: "tool",
            tool_call_id: toolCall.id,
            name: toolCall.function.name,
            content: result.success ? result.output : `Error: ${result.error}`
          });
          onEvent({
            type: "tool_result",
            step,
            toolResult: { toolCallId: toolCall.id, result }
          });
        }
      } else {
        keepRunning = false;
        onEvent({
          type: "finish",
          step,
          content: response.content
        });
      }
    }
    if (step >= maxSteps) {
      onEvent({
        type: "finish",
        step,
        content: `[Agent reached maximum step limit (${maxSteps})].`
      });
    }
    return messages;
  }
};

// src/tools/base.ts
var AgentTool = class {
  constructor() {
    /**
     * Indicates whether executing this tool modifies files in the Vault and requires strict confirmation.
     */
    this.isMutation = false;
  }
  /**
   * Returns clean JSON Schema representation of the tool.
   */
  toSchema() {
    return {
      name: this.name,
      description: this.description,
      parameters: this.parameters
    };
  }
};

// src/tools/vault/read-file.ts
var import_obsidian6 = require("obsidian");
var VaultReadFileTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_read_file";
    this.description = "Reads the content of a Markdown file or text document in the Obsidian Vault by path.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: 'Relative path of the file in the Vault (e.g. "Projects/Ideas.md")'
        }
      },
      required: ["path"]
    };
    this.isMutation = false;
  }
  async execute(args, app) {
    try {
      const file = app.vault.getAbstractFileByPath(args.path);
      if (!file || !(file instanceof import_obsidian6.TFile)) {
        return {
          success: false,
          output: "",
          error: `File not found at path: ${args.path}`
        };
      }
      const content = await app.vault.read(file);
      return {
        success: true,
        output: content
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error reading file ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/create-file.ts
var VaultCreateFileTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_create_file";
    this.description = "Creates a new Markdown file or document in the Vault at the specified path with initial content.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: 'Relative path for the new file in the Vault (e.g. "Notes/Daily-2026-08-13.md")'
        },
        content: {
          type: "string",
          description: "Text content to write into the new file"
        }
      },
      required: ["path", "content"]
    };
    this.isMutation = true;
  }
  async execute(args, app) {
    try {
      const existing = app.vault.getAbstractFileByPath(args.path);
      if (existing) {
        return {
          success: false,
          output: "",
          error: `A file or folder already exists at path: ${args.path}. Use vault_patch_file to modify existing files.`
        };
      }
      const pathParts = args.path.split("/");
      if (pathParts.length > 1) {
        const folderPath = pathParts.slice(0, -1).join("/");
        const folder = app.vault.getAbstractFileByPath(folderPath);
        if (!folder) {
          await app.vault.createFolder(folderPath);
        }
      }
      const createdFile = await app.vault.create(args.path, args.content || "");
      return {
        success: true,
        output: `File successfully created at ${createdFile.path} (${createdFile.stat.size} bytes).`
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error creating file ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/patch-file.ts
var import_obsidian7 = require("obsidian");
var VaultPatchFileTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_patch_file";
    this.description = "Updates or appends content to an existing file in the Vault.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: "Relative path of the existing file to update"
        },
        content: {
          type: "string",
          description: "New content to write or append"
        },
        mode: {
          type: "string",
          enum: ["overwrite", "append"],
          description: 'Mode of update: "overwrite" replaces entire content, "append" adds to the end of the file'
        }
      },
      required: ["path", "content", "mode"]
    };
    this.isMutation = true;
  }
  async execute(args, app) {
    try {
      const file = app.vault.getAbstractFileByPath(args.path);
      if (!file || !(file instanceof import_obsidian7.TFile)) {
        return {
          success: false,
          output: "",
          error: `File not found at path: ${args.path}`
        };
      }
      if (args.mode === "append") {
        await app.vault.append(file, "\n" + args.content);
        return {
          success: true,
          output: `Successfully appended content to ${file.path}.`
        };
      } else {
        await app.vault.modify(file, args.content);
        return {
          success: true,
          output: `Successfully overwritten content of ${file.path}.`
        };
      }
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error patching file ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/list-dir.ts
var import_obsidian8 = require("obsidian");
var VaultListDirTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_list_dir";
    this.description = "Lists all files and subfolders within a given Vault folder path.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: 'Relative path of the directory (use "" or "/" for root directory)'
        }
      },
      required: ["path"]
    };
    this.isMutation = false;
  }
  async execute(args, app) {
    try {
      const folderPath = (args.path || "").replace(/^\//, "");
      const folder = folderPath === "" ? app.vault.getRoot() : app.vault.getAbstractFileByPath(folderPath);
      if (!folder || !(folder instanceof import_obsidian8.TFolder)) {
        return {
          success: false,
          output: "",
          error: `Directory not found at path: "${args.path}"`
        };
      }
      const items = folder.children.map((child) => ({
        name: child.name,
        path: child.path,
        type: child instanceof import_obsidian8.TFolder ? "folder" : "file"
      }));
      return {
        success: true,
        output: JSON.stringify(items, null, 2)
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error listing directory ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/search-notes.ts
var VaultSearchNotesTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_search_notes";
    this.description = "Searches for notes in the Vault matching a search query string or keyword.";
    this.parameters = {
      type: "object",
      properties: {
        query: {
          type: "string",
          description: "Keyword or tag to search for in note paths or titles"
        }
      },
      required: ["query"]
    };
    this.isMutation = false;
  }
  async execute(args, app) {
    try {
      const queryLower = (args.query || "").toLowerCase();
      const files = app.vault.getMarkdownFiles();
      const matched = files.filter((file) => file.path.toLowerCase().includes(queryLower) || file.basename.toLowerCase().includes(queryLower)).map((file) => ({
        name: file.name,
        path: file.path,
        size: file.stat.size,
        mtime: file.stat.mtime
      })).slice(0, 20);
      return {
        success: true,
        output: JSON.stringify(matched, null, 2)
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error searching notes for "${args.query}": ${e.message}`
      };
    }
  }
};

// src/tools/registry.ts
var ToolRegistry = class {
  constructor() {
    this.tools = /* @__PURE__ */ new Map();
    this.registerTool(new VaultReadFileTool());
    this.registerTool(new VaultCreateFileTool());
    this.registerTool(new VaultPatchFileTool());
    this.registerTool(new VaultListDirTool());
    this.registerTool(new VaultSearchNotesTool());
  }
  registerTool(tool) {
    this.tools.set(tool.name, tool);
  }
  getTool(name) {
    return this.tools.get(name);
  }
  /**
   * Returns all registered tools as deterministically sorted ToolSchemas.
   */
  getSchemas() {
    const rawSchemas = Array.from(this.tools.values()).map((t) => t.toSchema());
    return sortToolSchemasDeterministically(rawSchemas);
  }
  async executeTool(name, args, app) {
    const tool = this.getTool(name);
    if (!tool) {
      return {
        success: false,
        output: "",
        error: `Unknown tool name: "${name}"`
      };
    }
    return await tool.execute(args, app);
  }
};

// src/utils/markdown-exporter.ts
var MarkdownExporter = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Exports conversation history to a formatted Markdown note in the "Agent Chats/" Vault folder.
   */
  async exportChatToMarkdown(messages, modelName) {
    const folderPath = "Agent Chats";
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await this.app.vault.createFolder(folderPath);
    }
    const now = /* @__PURE__ */ new Date();
    const dateStr = now.toISOString().replace(/T/, " ").replace(/\..+/, "");
    const fileDateStr = now.toISOString().slice(0, 10) + "-" + now.toTimeString().slice(0, 5).replace(":", "-");
    const filename = `${folderPath}/Agent Chat ${fileDateStr}.md`;
    let mdContent = `---
tags:
  - agent-chat
created: ${dateStr}
model: ${modelName}
---

# \u{1F916} Agent Chat Session (${dateStr})

`;
    for (const msg of messages) {
      if (msg.role === "user") {
        mdContent += `### \u{1F464} User
${msg.content}

`;
      } else if (msg.role === "assistant") {
        if (msg.content) {
          mdContent += `### \u{1F916} Assistant
${msg.content}

`;
        }
        if (msg.tool_calls && msg.tool_calls.length > 0) {
          mdContent += `> \u{1F6E0}\uFE0F **Tool Calls Requested:**
`;
          for (const tc of msg.tool_calls) {
            mdContent += `> - \`${tc.function.name}\` \`\`\`json
${tc.function.arguments}
\`\`\`
`;
          }
          mdContent += `
`;
        }
      } else if (msg.role === "tool") {
        mdContent += `> \u2699\uFE0F **Tool Result (${msg.name}):**
\`\`\`
${msg.content}
\`\`\`

`;
      }
    }
    const createdFile = await this.app.vault.create(filename, mdContent);
    return createdFile.path;
  }
};

// src/ui/components/confirmation-modal.ts
var import_obsidian9 = require("obsidian");
var ConfirmationModal = class extends import_obsidian9.Modal {
  constructor(app, toolCall, onResult) {
    super(app);
    this.toolCall = toolCall;
    this.onResult = onResult;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("harness-modal-content");
    contentEl.createEl("h3", { text: "\u26A0\uFE0F File Action Confirmation" });
    contentEl.createEl("p", {
      text: `The AI Agent is requesting permission to execute tool: "${this.toolCall.function.name}".`
    });
    const codeBlock = contentEl.createEl("pre");
    codeBlock.createEl("code", { text: this.toolCall.function.arguments });
    new import_obsidian9.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Deny").onClick(() => {
        this.onResult(false);
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Approve & Execute").setCta().onClick(() => {
        this.onResult(true);
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/chat-view.ts
var HARNESS_VIEW_TYPE = "harness-chat-view";
var HarnessChatView = class extends import_obsidian10.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.conversationHistory = [];
    this.plugin = plugin;
    this.toolRegistry = new ToolRegistry();
    this.agentHarness = new AgentHarness(this.app, this.plugin.settings, this.toolRegistry);
    this.exporter = new MarkdownExporter(this.app);
  }
  getViewType() {
    return HARNESS_VIEW_TYPE;
  }
  getDisplayText() {
    return "Agent Harness";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("harness-chat-container");
    const headerEl = container.createEl("div", { cls: "harness-chat-header" });
    headerEl.createEl("span", { text: "\u{1F916} Agent Harness", cls: "harness-title" });
    const actionsEl = headerEl.createEl("div", { cls: "harness-chat-header-actions" });
    this.providerSelectEl = actionsEl.createEl("select");
    const providers = [
      { id: "openrouter", label: "OpenRouter" },
      { id: "openai", label: "OpenAI" },
      { id: "anthropic", label: "Anthropic" },
      { id: "ollama", label: "Ollama" }
    ];
    for (const p of providers) {
      const opt = this.providerSelectEl.createEl("option", { value: p.id, text: p.label });
      if (p.id === this.plugin.settings.defaultProvider)
        opt.selected = true;
    }
    this.providerSelectEl.addEventListener("change", async () => {
      this.plugin.settings.defaultProvider = this.providerSelectEl.value;
      await this.plugin.saveSettings();
    });
    const exportBtn = actionsEl.createEl("button", { text: "\u{1F4E4} Export" });
    exportBtn.addEventListener("click", async () => {
      if (this.conversationHistory.length === 0) {
        new import_obsidian10.Notice("No chat history to export.");
        return;
      }
      try {
        const exportedPath = await this.exporter.exportChatToMarkdown(
          this.conversationHistory,
          this.plugin.settings.defaultModel
        );
        new import_obsidian10.Notice(`Chat exported to ${exportedPath}`);
      } catch (e) {
        new import_obsidian10.Notice(`Export failed: ${e.message}`);
      }
    });
    const clearBtn = actionsEl.createEl("button", { text: "\u{1F5D1}\uFE0F Clear" });
    clearBtn.addEventListener("click", () => {
      this.conversationHistory = [];
      this.renderMessages();
    });
    this.messagesContainerEl = container.createEl("div", { cls: "harness-chat-messages" });
    const inputAreaEl = container.createEl("div", { cls: "harness-chat-input-area" });
    const inputContainerEl = inputAreaEl.createEl("div", { cls: "harness-chat-input-container" });
    this.inputTextAreaEl = inputContainerEl.createEl("textarea", {
      cls: "harness-chat-textarea",
      placeholder: "Ask the Agent to inspect, search, or write notes..."
    });
    this.sendButtonEl = inputContainerEl.createEl("button", { text: "Send", cls: "mod-cta" });
    const handleSend = async () => {
      const text = this.inputTextAreaEl.value.trim();
      if (!text)
        return;
      this.inputTextAreaEl.value = "";
      this.sendButtonEl.disabled = true;
      const userMsg = { role: "user", content: text };
      this.conversationHistory.push(userMsg);
      this.renderMessages();
      const streamingMsgEl = this.messagesContainerEl.createEl("div", {
        cls: "harness-message harness-message-assistant"
      });
      streamingMsgEl.createEl("div", { text: "\u{1F916} Agent thinking...", cls: "harness-message-header" });
      const textContentEl = streamingMsgEl.createEl("div", { cls: "harness-message-body" });
      try {
        const updatedHistory = await this.agentHarness.runTurn(
          this.conversationHistory,
          (event) => {
            if (event.type === "chunk" && event.content) {
              textContentEl.setText(event.content);
              this.messagesContainerEl.scrollTop = this.messagesContainerEl.scrollHeight;
            } else if (event.type === "tool_call" && event.toolCall) {
              const card = this.messagesContainerEl.createEl("div", { cls: "harness-tool-card" });
              card.createEl("div", {
                text: `\u{1F6E0}\uFE0F Tool requested: ${event.toolCall.function.name}`,
                cls: "harness-tool-title"
              });
            }
          },
          (toolCall) => {
            return new Promise((resolve) => {
              new ConfirmationModal(this.app, toolCall, resolve).open();
            });
          }
        );
        this.conversationHistory = updatedHistory;
      } catch (err) {
        new import_obsidian10.Notice(`Agent error: ${err.message}`);
        textContentEl.setText(`\u26A0\uFE0F Error: ${err.message}`);
      } finally {
        this.sendButtonEl.disabled = false;
        this.renderMessages();
      }
    };
    this.sendButtonEl.addEventListener("click", handleSend);
    this.inputTextAreaEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        handleSend();
      }
    });
    this.renderMessages();
  }
  renderMessages() {
    if (!this.messagesContainerEl)
      return;
    this.messagesContainerEl.empty();
    if (this.conversationHistory.length === 0) {
      const emptyEl = this.messagesContainerEl.createEl("div", {
        cls: "harness-empty-state",
        text: "No active conversation. Type a message below to start the Agent Harness."
      });
      emptyEl.style.opacity = "0.6";
      emptyEl.style.textAlign = "center";
      emptyEl.style.padding = "32px 16px";
      return;
    }
    for (const msg of this.conversationHistory) {
      if (msg.role === "user") {
        const msgEl = this.messagesContainerEl.createEl("div", { cls: "harness-message harness-message-user" });
        msgEl.createEl("div", { text: "\u{1F464} You", cls: "harness-message-header" });
        msgEl.createEl("div", { text: typeof msg.content === "string" ? msg.content : JSON.stringify(msg.content || ""), cls: "harness-message-body" });
      } else if (msg.role === "assistant") {
        if (msg.content) {
          const msgEl = this.messagesContainerEl.createEl("div", { cls: "harness-message harness-message-assistant" });
          msgEl.createEl("div", { text: "\u{1F916} Agent", cls: "harness-message-header" });
          msgEl.createEl("div", { text: typeof msg.content === "string" ? msg.content : JSON.stringify(msg.content || ""), cls: "harness-message-body" });
        }
        if (msg.tool_calls) {
          for (const tc of msg.tool_calls) {
            const card = this.messagesContainerEl.createEl("div", { cls: "harness-tool-card" });
            card.createEl("div", { text: `\u{1F6E0}\uFE0F Tool: ${tc.function.name}`, cls: "harness-tool-title" });
            const argsPre = card.createEl("pre");
            argsPre.createEl("code", { text: tc.function.arguments });
          }
        }
      } else if (msg.role === "tool") {
        const card = this.messagesContainerEl.createEl("div", { cls: "harness-tool-card" });
        card.createEl("div", { text: `\u2699\uFE0F Tool Output (${msg.name})`, cls: "harness-tool-title" });
        const outPre = card.createEl("pre");
        outPre.createEl("code", { text: typeof msg.content === "string" ? msg.content : JSON.stringify(msg.content || "") });
      }
    }
    this.messagesContainerEl.scrollTop = this.messagesContainerEl.scrollHeight;
  }
  async onClose() {
  }
};

// src/main.ts
var HarnessPlugin = class extends import_obsidian11.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(HARNESS_VIEW_TYPE, (leaf) => new HarnessChatView(leaf, this));
    this.addRibbonIcon("bot", "Open Agent Harness Chat", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-agent-harness-chat",
      name: "Open Agent Harness Chat",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new HarnessSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(HARNESS_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: HARNESS_VIEW_TYPE,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
