/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HarnessPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian13 = require("obsidian");

// src/types.ts
var DEFAULT_PROVIDERS = [
  {
    id: "openrouter",
    name: "OpenRouter",
    type: "openrouter",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeySecretName: "oh_bot_secret_openrouter",
    models: [
      "anthropic/claude-3.7-sonnet",
      "anthropic/claude-3.5-haiku",
      "openai/gpt-4o",
      "openai/gpt-4o-mini",
      "deepseek/deepseek-r1",
      "google/gemini-2.5-flash",
      "meta-llama/llama-3.3-70b-instruct"
    ],
    enabled: true
  },
  {
    id: "anthropic",
    name: "Anthropic",
    type: "anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    apiKeySecretName: "oh_bot_secret_anthropic",
    models: [
      "claude-3-7-sonnet-20250219",
      "claude-3-5-sonnet-20241022",
      "claude-3-5-haiku-20241022"
    ],
    enabled: true
  },
  {
    id: "gemini",
    name: "Google Gemini (AI Studio)",
    type: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai/",
    apiKeySecretName: "oh_bot_secret_gemini",
    models: [
      "gemini-2.5-flash",
      "gemini-2.5-pro",
      "gemini-2.0-flash",
      "gemini-1.5-pro",
      "gemini-1.5-flash"
    ],
    enabled: true
  },
  {
    id: "openai",
    name: "OpenAI",
    type: "openai",
    baseUrl: "https://api.openai.com/v1",
    apiKeySecretName: "oh_bot_secret_openai",
    models: [
      "gpt-4o",
      "gpt-4o-mini",
      "gpt-4.5-preview",
      "o3-mini",
      "o1"
    ],
    enabled: true
  },
  {
    id: "ollama",
    name: "Ollama (Local)",
    type: "ollama",
    baseUrl: "http://localhost:11434/v1",
    apiKeySecretName: "oh_bot_secret_ollama",
    models: [
      "llama3.3",
      "qwen2.5-coder",
      "deepseek-r1",
      "mistral"
    ],
    enabled: true
  }
];
var DEFAULT_SETTINGS = {
  providers: DEFAULT_PROVIDERS,
  activeProviderId: "openrouter",
  activeModel: "anthropic/claude-3.7-sonnet",
  systemPrompt: "You are an autonomous AI Agent inside Obsidian. You have tools to read, create, patch, search, and inspect notes in the vault. Use these tools step-by-step to fulfill the user request.",
  safetyMode: "strict"
};

// src/ui/settings-tab.ts
var import_obsidian3 = require("obsidian");

// src/ui/components/add-provider-modal.ts
var import_obsidian2 = require("obsidian");

// src/utils/model-fetcher.ts
var import_obsidian = require("obsidian");
async function fetchAvailableModels(baseUrl, apiKey) {
  try {
    let cleanBase = baseUrl.replace(/\/+$/, "");
    if (!cleanBase.endsWith("/models")) {
      cleanBase = cleanBase + "/models";
    }
    const headers = {
      "Content-Type": "application/json"
    };
    if (apiKey) {
      headers["Authorization"] = `Bearer ${apiKey}`;
    }
    const res = await (0, import_obsidian.requestUrl)({
      url: cleanBase,
      method: "GET",
      headers
    });
    const data = res.json;
    if (data && Array.isArray(data.data)) {
      return data.data.map((m) => m.id || m.name).filter((id) => typeof id === "string").sort();
    } else if (Array.isArray(data)) {
      return data.map((m) => typeof m === "string" ? m : m.id || m.name).filter((id) => typeof id === "string").sort();
    }
    return [];
  } catch (err) {
    console.error("Failed to fetch models from endpoint:", err);
    return [];
  }
}

// src/utils/secrets.ts
var SecretManager = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Retrieves the secret value associated with the given secret name using SecretStorage API.
   */
  getSecret(secretName) {
    if (!secretName) {
      return null;
    }
    const secretStorage = this.app.secretStorage;
    if (secretStorage && typeof secretStorage.getSecret === "function") {
      const secret = secretStorage.getSecret(secretName);
      return secret || null;
    }
    return null;
  }
};

// src/ui/components/add-provider-modal.ts
var AddProviderModal = class extends import_obsidian2.Modal {
  constructor(app, onAdd) {
    super(app);
    this.providerName = "";
    this.baseUrl = "https://api.openai.com/v1";
    this.secretName = `oh_bot_secret_custom_${Date.now()}`;
    this.modelsStr = "";
    this.onAdd = onAdd;
    this.secretManager = new SecretManager(app);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("harness-modal-content");
    contentEl.createEl("h2", { text: "Add Custom OpenAI-Compatible Provider" });
    new import_obsidian2.Setting(contentEl).setName("Provider Name").setDesc("e.g. DeepSeek, Groq, Together AI, LM Studio").addText(
      (text) => text.setPlaceholder("My Custom Provider").onChange((val) => {
        this.providerName = val.trim();
      })
    );
    new import_obsidian2.Setting(contentEl).setName("Base URL").setDesc("API Base URL (e.g. https://api.deepseek.com/v1 or http://localhost:1234/v1)").addText(
      (text) => text.setValue(this.baseUrl).onChange((val) => {
        this.baseUrl = val.trim();
      })
    );
    new import_obsidian2.Setting(contentEl).setName("API Key Secret").setDesc("Select or store secret in Obsidian SecretStorage").addComponent((el) => {
      try {
        return new import_obsidian2.SecretComponent(this.app, el).setValue(this.secretName).onChange((val) => {
          this.secretName = val;
        });
      } catch {
        const input = el.createEl("input", { type: "password", value: this.secretName });
        input.addEventListener("change", (e) => {
          this.secretName = e.target.value;
        });
        return el;
      }
    });
    new import_obsidian2.Setting(contentEl).setName("Models (comma separated)").setDesc("e.g. deepseek-chat, deepseek-reasoner").addTextArea((text) => {
      text.setPlaceholder("model-1, model-2").onChange((val) => {
        this.modelsStr = val;
      });
    }).addButton(
      (btn) => btn.setButtonText("\u{1F504} Auto-Fetch Models").onClick(async () => {
        const apiKey = this.secretManager.getSecret(this.secretName) || "";
        new import_obsidian2.Notice("Fetching models from endpoint...");
        const fetched = await fetchAvailableModels(this.baseUrl, apiKey);
        if (fetched.length > 0) {
          this.modelsStr = fetched.join(", ");
          new import_obsidian2.Notice(`Found ${fetched.length} models!`);
          this.onOpen();
        } else {
          new import_obsidian2.Notice("Could not fetch models automatically. Please enter model names manually.");
        }
      })
    );
    new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Save Provider").setCta().onClick(async () => {
        if (!this.providerName) {
          new import_obsidian2.Notice("Please enter a provider name.");
          return;
        }
        const modelList = this.modelsStr.split(",").map((m) => m.trim()).filter((m) => m.length > 0);
        const newProvider = {
          id: `custom_${Date.now()}`,
          name: this.providerName,
          type: "custom-openai",
          baseUrl: this.baseUrl,
          apiKeySecretName: this.secretName,
          models: modelList.length > 0 ? modelList : ["default-model"],
          enabled: true,
          isCustom: true
        };
        await this.onAdd(newProvider);
        new import_obsidian2.Notice(`Provider "${this.providerName}" added!`);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/ui/settings-tab.ts
var HarnessSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.secretManager = new SecretManager(app);
    this.selectedConfigProviderId = this.plugin.settings.activeProviderId || this.plugin.settings.providers[0]?.id || "openrouter";
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Obsidian Harness Bot Settings" });
    new import_obsidian3.Setting(containerEl).setName("Default Active Provider").setDesc("Select the default AI provider for agent operations").addDropdown((dropdown) => {
      for (const prov of this.plugin.settings.providers) {
        dropdown.addOption(prov.id, prov.name);
      }
      dropdown.setValue(this.plugin.settings.activeProviderId);
      dropdown.onChange(async (val) => {
        this.plugin.settings.activeProviderId = val;
        const activeProv = this.plugin.settings.providers.find((p) => p.id === val);
        if (activeProv && activeProv.models.length > 0) {
          this.plugin.settings.activeModel = activeProv.models[0];
        }
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const currentActiveProvider = this.plugin.settings.providers.find(
      (p) => p.id === this.plugin.settings.activeProviderId
    ) || this.plugin.settings.providers[0];
    new import_obsidian3.Setting(containerEl).setName("Default Active Model").setDesc(`Select model for ${currentActiveProvider?.name || "current provider"}`).addDropdown((dropdown) => {
      const models = currentActiveProvider?.models || [];
      for (const m of models) {
        dropdown.addOption(m, m);
      }
      if (models.includes(this.plugin.settings.activeModel)) {
        dropdown.setValue(this.plugin.settings.activeModel);
      } else if (models.length > 0) {
        dropdown.setValue(models[0]);
      }
      dropdown.onChange(async (val) => {
        this.plugin.settings.activeModel = val;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "Provider Configuration" });
    new import_obsidian3.Setting(containerEl).setName("Select Provider to Configure").setDesc("Choose a provider from the list to update its API key, base URL, or model list").addDropdown((dropdown) => {
      for (const prov of this.plugin.settings.providers) {
        dropdown.addOption(prov.id, prov.name);
      }
      dropdown.setValue(this.selectedConfigProviderId);
      dropdown.onChange((val) => {
        this.selectedConfigProviderId = val;
        this.display();
      });
    }).addButton(
      (btn) => btn.setButtonText("+ Add Custom Provider").setCta().onClick(() => {
        new AddProviderModal(this.app, async (newProvider) => {
          this.plugin.settings.providers.push(newProvider);
          this.selectedConfigProviderId = newProvider.id;
          await this.plugin.saveSettings();
          this.display();
        }).open();
      })
    );
    const configProvider = this.plugin.settings.providers.find(
      (p) => p.id === this.selectedConfigProviderId
    );
    if (configProvider) {
      const providerCardEl = containerEl.createEl("div", { cls: "harness-provider-card" });
      providerCardEl.style.border = "1px solid var(--background-modifier-border)";
      providerCardEl.style.borderRadius = "8px";
      providerCardEl.style.padding = "12px";
      providerCardEl.style.marginBottom = "16px";
      providerCardEl.style.backgroundColor = "var(--background-secondary)";
      providerCardEl.createEl("h4", { text: `\u2699\uFE0F Settings for: ${configProvider.name}` });
      new import_obsidian3.Setting(providerCardEl).setName("Base URL").setDesc("Endpoint URL for this provider").addText(
        (text) => text.setValue(configProvider.baseUrl).onChange(async (val) => {
          configProvider.baseUrl = val.trim();
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian3.Setting(providerCardEl).setName("API Key Secret").setDesc(`Stored in Obsidian SecretStorage under ID: "${configProvider.apiKeySecretName}"`).addComponent((el) => {
        try {
          return new import_obsidian3.SecretComponent(this.app, el).setValue(configProvider.apiKeySecretName).onChange(async (val) => {
            configProvider.apiKeySecretName = val;
            await this.plugin.saveSettings();
          });
        } catch {
          const input = el.createEl("input", { type: "password", value: configProvider.apiKeySecretName });
          input.addEventListener("change", async (ev) => {
            configProvider.apiKeySecretName = ev.target.value;
            await this.plugin.saveSettings();
          });
          return el;
        }
      });
      new import_obsidian3.Setting(providerCardEl).setName("Available Models").setDesc("Comma-separated list of model identifiers").addTextArea(
        (text) => text.setValue(configProvider.models.join(", ")).onChange(async (val) => {
          configProvider.models = val.split(",").map((m) => m.trim()).filter((m) => m.length > 0);
          await this.plugin.saveSettings();
        })
      ).addButton(
        (btn) => btn.setButtonText("\u{1F504} Fetch Models from Endpoint").onClick(async () => {
          const apiKey = this.secretManager.getSecret(configProvider.apiKeySecretName) || "";
          new import_obsidian3.Notice(`Fetching models for ${configProvider.name}...`);
          const fetched = await fetchAvailableModels(configProvider.baseUrl, apiKey);
          if (fetched.length > 0) {
            configProvider.models = fetched;
            await this.plugin.saveSettings();
            new import_obsidian3.Notice(`Updated ${configProvider.name} with ${fetched.length} models!`);
            this.display();
          } else {
            new import_obsidian3.Notice("Could not fetch models automatically from endpoint.");
          }
        })
      );
      if (configProvider.isCustom) {
        new import_obsidian3.Setting(providerCardEl).setName("Delete Provider").setDesc("Remove this custom provider from your settings").addButton(
          (btn) => btn.setButtonText("\u{1F5D1}\uFE0F Delete Provider").setWarning().onClick(async () => {
            this.plugin.settings.providers = this.plugin.settings.providers.filter(
              (p) => p.id !== configProvider.id
            );
            this.selectedConfigProviderId = this.plugin.settings.providers[0]?.id || "openrouter";
            if (this.plugin.settings.activeProviderId === configProvider.id) {
              this.plugin.settings.activeProviderId = this.selectedConfigProviderId;
            }
            await this.plugin.saveSettings();
            new import_obsidian3.Notice(`Deleted provider "${configProvider.name}".`);
            this.display();
          })
        );
      }
    }
    containerEl.createEl("h3", { text: "General & Safety" });
    new import_obsidian3.Setting(containerEl).setName("Vault Modification Safety Mode").setDesc("Strict mode prompts for user confirmation before writing or modifying any Vault file").addDropdown(
      (dropdown) => dropdown.addOption("strict", "Strict (Prompt before file edits)").addOption("auto", "Auto (Auto-approve file edits)").setValue(this.plugin.settings.safetyMode).onChange(async (value) => {
        this.plugin.settings.safetyMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("System Prompt").setDesc("Base instructions for the Agent Harness").addTextArea(
      (text) => text.setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/ui/chat-view.ts
var import_obsidian12 = require("obsidian");

// src/engine/providers/base.ts
var LLMProvider = class {
};

// src/utils/cache-helpers.ts
function sortToolSchemasDeterministically(tools) {
  return [...tools].sort((a, b) => a.name.localeCompare(b.name)).map((tool) => {
    const properties = tool.parameters.properties;
    const sortedPropertyKeys = Object.keys(properties).sort();
    const sortedProperties = {};
    for (const key of sortedPropertyKeys) {
      sortedProperties[key] = properties[key];
    }
    return {
      ...tool,
      parameters: {
        ...tool.parameters,
        properties: sortedProperties,
        required: tool.parameters.required ? [...tool.parameters.required].sort() : void 0
      }
    };
  });
}
function prepareNetworkPayloadMessages(messages) {
  if (messages.length === 0)
    return [];
  const networkMessages = JSON.parse(JSON.stringify(messages));
  for (let i = networkMessages.length - 1; i >= 0; i--) {
    if (networkMessages[i].role === "user" && typeof networkMessages[i].content === "string") {
      const nowIso = (/* @__PURE__ */ new Date()).toISOString();
      networkMessages[i].content = `${networkMessages[i].content}

[Current Date & Time: ${nowIso}]`;
      break;
    }
  }
  return networkMessages;
}

// src/engine/stream-parser.ts
var SSEStreamParser = class {
  constructor() {
    this.buffer = "";
  }
  /**
   * Processes a chunk of string text and extracts completed SSE event lines.
   */
  feed(chunk) {
    this.buffer += chunk;
    const events = [];
    const lines = this.buffer.split("\n");
    this.buffer = lines.pop() || "";
    let currentEvent = {};
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) {
        if (currentEvent.data !== void 0) {
          events.push(currentEvent);
          currentEvent = {};
        }
        continue;
      }
      if (trimmed.startsWith("event:")) {
        currentEvent.event = trimmed.substring(6).trim();
      } else if (trimmed.startsWith("data:")) {
        const dataPart = trimmed.substring(5).trim();
        if (currentEvent.data) {
          currentEvent.data += "\n" + dataPart;
        } else {
          currentEvent.data = dataPart;
        }
      }
    }
    return events;
  }
};

// src/engine/providers/openrouter.ts
var import_obsidian4 = require("obsidian");
var OpenRouterProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "openrouter";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk) {
    const endpoint = (baseUrl || "https://openrouter.ai/api/v1").replace(/\/$/, "") + "/chat/completions";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = [
      { role: "system", content: systemPrompt },
      ...networkMessages
    ];
    const formattedTools = sortedTools.map((t) => ({
      type: "function",
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }));
    const payload = {
      model: model || "anthropic/claude-3.7-sonnet",
      messages: formattedMessages,
      stream: true
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`,
          "HTTP-Referer": "https://github.com/killery/obsidian-harness-bot",
          "X-Title": "Obsidian Agent Harness"
        },
        body: JSON.stringify(payload)
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`OpenRouter HTTP ${response.status}: ${errorText}`);
      }
      const reader = response.body?.getReader();
      const decoder = new TextDecoder("utf-8");
      const parser = new SSEStreamParser();
      let fullContent = "";
      const toolCallMap = {};
      if (reader) {
        while (true) {
          const { done, value } = await reader.read();
          if (done)
            break;
          const text = decoder.decode(value, { stream: true });
          const events = parser.feed(text);
          for (const ev of events) {
            if (ev.data === "[DONE]")
              continue;
            try {
              const parsed = JSON.parse(ev.data);
              const delta = parsed.choices?.[0]?.delta;
              if (delta?.content) {
                fullContent += delta.content;
                if (onChunk)
                  onChunk(delta.content);
              }
              if (delta?.tool_calls) {
                for (const tc of delta.tool_calls) {
                  const idx = tc.index ?? 0;
                  if (!toolCallMap[idx]) {
                    toolCallMap[idx] = { id: tc.id || "", name: tc.function?.name || "", args: "" };
                  }
                  if (tc.id)
                    toolCallMap[idx].id = tc.id;
                  if (tc.function?.name)
                    toolCallMap[idx].name = tc.function.name;
                  if (tc.function?.arguments)
                    toolCallMap[idx].args += tc.function.arguments;
                }
              }
            } catch (e) {
            }
          }
        }
      }
      const finalToolCalls = Object.values(toolCallMap).map((tc) => ({
        id: tc.id,
        type: "function",
        function: {
          name: tc.name,
          arguments: tc.args
        }
      }));
      return {
        content: fullContent,
        toolCalls: finalToolCalls.length > 0 ? finalToolCalls : void 0
      };
    } catch (err) {
      const reqRes = await (0, import_obsidian4.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({ ...payload, stream: false })
      });
      const resJson = reqRes.json;
      const choice = resJson.choices?.[0]?.message;
      return {
        content: choice?.content || "",
        toolCalls: choice?.tool_calls
      };
    }
  }
};

// src/engine/providers/openai.ts
var import_obsidian5 = require("obsidian");
var OpenAIProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "openai";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk) {
    const endpoint = (baseUrl || "https://api.openai.com/v1").replace(/\/$/, "") + "/chat/completions";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = [
      { role: "system", content: systemPrompt },
      ...networkMessages
    ];
    const formattedTools = sortedTools.map((t) => ({
      type: "function",
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }));
    const payload = {
      model: model || "gpt-4o",
      messages: formattedMessages,
      stream: true
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify(payload)
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`OpenAI HTTP ${response.status}: ${errorText}`);
      }
      const reader = response.body?.getReader();
      const decoder = new TextDecoder("utf-8");
      const parser = new SSEStreamParser();
      let fullContent = "";
      const toolCallMap = {};
      if (reader) {
        while (true) {
          const { done, value } = await reader.read();
          if (done)
            break;
          const text = decoder.decode(value, { stream: true });
          const events = parser.feed(text);
          for (const ev of events) {
            if (ev.data === "[DONE]")
              continue;
            try {
              const parsed = JSON.parse(ev.data);
              const delta = parsed.choices?.[0]?.delta;
              if (delta?.content) {
                fullContent += delta.content;
                if (onChunk)
                  onChunk(delta.content);
              }
              if (delta?.tool_calls) {
                for (const tc of delta.tool_calls) {
                  const idx = tc.index ?? 0;
                  if (!toolCallMap[idx]) {
                    toolCallMap[idx] = { id: tc.id || "", name: tc.function?.name || "", args: "" };
                  }
                  if (tc.id)
                    toolCallMap[idx].id = tc.id;
                  if (tc.function?.name)
                    toolCallMap[idx].name = tc.function.name;
                  if (tc.function?.arguments)
                    toolCallMap[idx].args += tc.function.arguments;
                }
              }
            } catch (e) {
            }
          }
        }
      }
      const finalToolCalls = Object.values(toolCallMap).map((tc) => ({
        id: tc.id,
        type: "function",
        function: {
          name: tc.name,
          arguments: tc.args
        }
      }));
      return {
        content: fullContent,
        toolCalls: finalToolCalls.length > 0 ? finalToolCalls : void 0
      };
    } catch (err) {
      const reqRes = await (0, import_obsidian5.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({ ...payload, stream: false })
      });
      const resJson = reqRes.json;
      const choice = resJson.choices?.[0]?.message;
      return {
        content: choice?.content || "",
        toolCalls: choice?.tool_calls
      };
    }
  }
};

// src/engine/providers/anthropic.ts
var import_obsidian6 = require("obsidian");
var AnthropicProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "anthropic";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk) {
    const endpoint = (baseUrl || "https://api.anthropic.com/v1").replace(/\/$/, "") + "/messages";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = networkMessages.map((msg) => ({
      role: msg.role === "assistant" ? "assistant" : "user",
      content: msg.content
    }));
    const formattedTools = sortedTools.map((t) => ({
      name: t.name,
      description: t.description,
      input_schema: t.parameters
    }));
    const payload = {
      model: model || "claude-3-7-sonnet-20250219",
      max_tokens: 4096,
      system: [
        {
          type: "text",
          text: systemPrompt,
          cache_control: { type: "ephemeral" }
        }
      ],
      messages: formattedMessages,
      stream: true
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01",
          "anthropic-beta": "prompt-caching-2024-07-31"
        },
        body: JSON.stringify(payload)
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Anthropic HTTP ${response.status}: ${errorText}`);
      }
      const reader = response.body?.getReader();
      const decoder = new TextDecoder("utf-8");
      const parser = new SSEStreamParser();
      let fullContent = "";
      const toolCallList = [];
      let currentToolCall = null;
      if (reader) {
        while (true) {
          const { done, value } = await reader.read();
          if (done)
            break;
          const text = decoder.decode(value, { stream: true });
          const events = parser.feed(text);
          for (const ev of events) {
            try {
              const parsed = JSON.parse(ev.data);
              if (parsed.type === "content_block_delta") {
                if (parsed.delta?.type === "text_delta") {
                  const chunk = parsed.delta.text;
                  fullContent += chunk;
                  if (onChunk)
                    onChunk(chunk);
                } else if (parsed.delta?.type === "input_json_delta") {
                  if (currentToolCall) {
                    currentToolCall.argsStr += parsed.delta.partial_json;
                  }
                }
              } else if (parsed.type === "content_block_start") {
                if (parsed.content_block?.type === "tool_use") {
                  currentToolCall = {
                    id: parsed.content_block.id,
                    name: parsed.content_block.name,
                    argsStr: ""
                  };
                }
              } else if (parsed.type === "content_block_stop") {
                if (currentToolCall) {
                  toolCallList.push({
                    id: currentToolCall.id,
                    type: "function",
                    function: {
                      name: currentToolCall.name,
                      arguments: currentToolCall.argsStr
                    }
                  });
                  currentToolCall = null;
                }
              }
            } catch (e) {
            }
          }
        }
      }
      return {
        content: fullContent,
        toolCalls: toolCallList.length > 0 ? toolCallList : void 0
      };
    } catch (err) {
      const reqRes = await (0, import_obsidian6.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify({ ...payload, stream: false })
      });
      const resJson = reqRes.json;
      let textContent = "";
      const toolCalls = [];
      for (const block of resJson.content || []) {
        if (block.type === "text") {
          textContent += block.text;
        } else if (block.type === "tool_use") {
          toolCalls.push({
            id: block.id,
            type: "function",
            function: {
              name: block.name,
              arguments: JSON.stringify(block.input)
            }
          });
        }
      }
      return {
        content: textContent,
        toolCalls: toolCalls.length > 0 ? toolCalls : void 0
      };
    }
  }
};

// src/engine/providers/ollama.ts
var import_obsidian7 = require("obsidian");
var OllamaProvider = class extends LLMProvider {
  constructor() {
    super(...arguments);
    this.name = "ollama";
  }
  async chatCompletion(apiKey, baseUrl, model, systemPrompt, messages, tools, onChunk) {
    const endpoint = (baseUrl || "http://localhost:11434/v1").replace(/\/$/, "") + "/chat/completions";
    const sortedTools = sortToolSchemasDeterministically(tools);
    const networkMessages = prepareNetworkPayloadMessages(messages);
    const formattedMessages = [
      { role: "system", content: systemPrompt },
      ...networkMessages
    ];
    const formattedTools = sortedTools.map((t) => ({
      type: "function",
      function: {
        name: t.name,
        description: t.description,
        parameters: t.parameters
      }
    }));
    const payload = {
      model: model || "llama3",
      messages: formattedMessages,
      stream: false
    };
    if (formattedTools.length > 0) {
      payload.tools = formattedTools;
    }
    const headers = {
      "Content-Type": "application/json"
    };
    if (apiKey) {
      headers["Authorization"] = `Bearer ${apiKey}`;
    }
    const reqRes = await (0, import_obsidian7.requestUrl)({
      url: endpoint,
      method: "POST",
      headers,
      body: JSON.stringify(payload)
    });
    const resJson = reqRes.json;
    const choice = resJson.choices?.[0]?.message;
    if (choice?.content && onChunk) {
      onChunk(choice.content);
    }
    const toolCalls = (choice?.tool_calls || []).map((tc) => ({
      id: tc.id || `call_${Date.now()}`,
      type: "function",
      function: {
        name: tc.function?.name || "",
        arguments: typeof tc.function?.arguments === "string" ? tc.function.arguments : JSON.stringify(tc.function?.arguments || {})
      }
    }));
    return {
      content: choice?.content || "",
      toolCalls: toolCalls.length > 0 ? toolCalls : void 0
    };
  }
};

// src/engine/agent.ts
var AgentHarness = class {
  constructor(app, settings, toolRegistry) {
    this.providers = /* @__PURE__ */ new Map();
    this.app = app;
    this.settings = settings;
    this.secretManager = new SecretManager(app);
    this.toolRegistry = toolRegistry;
    this.providers.set("openrouter", new OpenRouterProvider());
    this.providers.set("openai", new OpenAIProvider());
    this.providers.set("gemini", new OpenAIProvider());
    this.providers.set("custom-openai", new OpenAIProvider());
    this.providers.set("anthropic", new AnthropicProvider());
    this.providers.set("ollama", new OllamaProvider());
  }
  getActiveProviderConfig(providerId) {
    const targetId = providerId || this.settings.activeProviderId || "openrouter";
    const config = this.settings.providers.find((p) => p.id === targetId) || this.settings.providers[0];
    if (!config) {
      throw new Error(`No provider found for ID "${targetId}"`);
    }
    let provider = this.providers.get(config.type);
    if (!provider) {
      provider = this.providers.get("openai");
    }
    if (!provider) {
      throw new Error(`Unsupported provider type: ${config.type}`);
    }
    const apiKey = config.apiKeySecretName ? this.secretManager.getSecret(config.apiKeySecretName) || "" : "";
    if (config.type !== "ollama" && !apiKey) {
      throw new Error(`No API key found for provider "${config.name}". Please set it in Settings.`);
    }
    return { provider, config, apiKey };
  }
  /**
   * Runs the multi-step agent turn loop.
   */
  async runTurn(history, onEvent, onConfirm, overrideProviderId, overrideModel) {
    const { provider, config, apiKey } = this.getActiveProviderConfig(overrideProviderId);
    const model = overrideModel || this.settings.activeModel || config.models[0] || "anthropic/claude-3.7-sonnet";
    const messages = [...history];
    const tools = this.toolRegistry.getSchemas();
    const maxSteps = 25;
    let step = 0;
    let keepRunning = true;
    while (keepRunning && step < maxSteps) {
      step++;
      let streamContent = "";
      const response = await provider.chatCompletion(
        apiKey,
        config.baseUrl,
        model,
        this.settings.systemPrompt,
        messages,
        tools,
        (chunk) => {
          streamContent += chunk;
          onEvent({
            type: "chunk",
            step,
            content: streamContent
          });
        }
      );
      const assistantMessage = {
        role: "assistant",
        content: response.content || "",
        tool_calls: response.toolCalls
      };
      messages.push(assistantMessage);
      if (response.toolCalls && response.toolCalls.length > 0) {
        for (const toolCall of response.toolCalls) {
          onEvent({
            type: "tool_call",
            step,
            toolCall
          });
          const toolInstance = this.toolRegistry.getTool(toolCall.function.name);
          if (toolInstance?.isMutation && this.settings.safetyMode === "strict") {
            onEvent({
              type: "awaiting_confirmation",
              step,
              toolCall
            });
            if (onConfirm) {
              const approved = await onConfirm(toolCall);
              if (!approved) {
                const cancelledResult = {
                  success: false,
                  output: "",
                  error: "User denied file modification permission for this tool execution."
                };
                messages.push({
                  role: "tool",
                  tool_call_id: toolCall.id,
                  name: toolCall.function.name,
                  content: JSON.stringify(cancelledResult)
                });
                onEvent({
                  type: "tool_result",
                  step,
                  toolResult: { toolCallId: toolCall.id, result: cancelledResult }
                });
                continue;
              }
            }
          }
          let parsedArgs = {};
          try {
            parsedArgs = JSON.parse(toolCall.function.arguments || "{}");
          } catch (e) {
            parsedArgs = {};
          }
          const result = await this.toolRegistry.executeTool(toolCall.function.name, parsedArgs, this.app);
          messages.push({
            role: "tool",
            tool_call_id: toolCall.id,
            name: toolCall.function.name,
            content: result.success ? result.output : `Error: ${result.error}`
          });
          onEvent({
            type: "tool_result",
            step,
            toolResult: { toolCallId: toolCall.id, result }
          });
        }
      } else {
        keepRunning = false;
        onEvent({
          type: "finish",
          step,
          content: response.content
        });
      }
    }
    if (step >= maxSteps) {
      onEvent({
        type: "finish",
        step,
        content: `[Agent reached maximum step limit (${maxSteps})].`
      });
    }
    return messages;
  }
};

// src/tools/base.ts
var AgentTool = class {
  constructor() {
    /**
     * Indicates whether executing this tool modifies files in the Vault and requires strict confirmation.
     */
    this.isMutation = false;
  }
  /**
   * Returns clean JSON Schema representation of the tool.
   */
  toSchema() {
    return {
      name: this.name,
      description: this.description,
      parameters: this.parameters
    };
  }
};

// src/tools/vault/read-file.ts
var import_obsidian8 = require("obsidian");
var VaultReadFileTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_read_file";
    this.description = "Reads the content of a Markdown file or text document in the Obsidian Vault by path.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: 'Relative path of the file in the Vault (e.g. "Projects/Ideas.md")'
        }
      },
      required: ["path"]
    };
    this.isMutation = false;
  }
  async execute(args, app) {
    try {
      const file = app.vault.getAbstractFileByPath(args.path);
      if (!file || !(file instanceof import_obsidian8.TFile)) {
        return {
          success: false,
          output: "",
          error: `File not found at path: ${args.path}`
        };
      }
      const content = await app.vault.read(file);
      return {
        success: true,
        output: content
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error reading file ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/create-file.ts
var VaultCreateFileTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_create_file";
    this.description = "Creates a new Markdown file or document in the Vault at the specified path with initial content.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: 'Relative path for the new file in the Vault (e.g. "Notes/Daily-2026-08-13.md")'
        },
        content: {
          type: "string",
          description: "Text content to write into the new file"
        }
      },
      required: ["path", "content"]
    };
    this.isMutation = true;
  }
  async execute(args, app) {
    try {
      const existing = app.vault.getAbstractFileByPath(args.path);
      if (existing) {
        return {
          success: false,
          output: "",
          error: `A file or folder already exists at path: ${args.path}. Use vault_patch_file to modify existing files.`
        };
      }
      const pathParts = args.path.split("/");
      if (pathParts.length > 1) {
        const folderPath = pathParts.slice(0, -1).join("/");
        const folder = app.vault.getAbstractFileByPath(folderPath);
        if (!folder) {
          await app.vault.createFolder(folderPath);
        }
      }
      const createdFile = await app.vault.create(args.path, args.content || "");
      return {
        success: true,
        output: `File successfully created at ${createdFile.path} (${createdFile.stat.size} bytes).`
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error creating file ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/patch-file.ts
var import_obsidian9 = require("obsidian");
var VaultPatchFileTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_patch_file";
    this.description = "Updates or appends content to an existing file in the Vault.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: "Relative path of the existing file to update"
        },
        content: {
          type: "string",
          description: "New content to write or append"
        },
        mode: {
          type: "string",
          enum: ["overwrite", "append"],
          description: 'Mode of update: "overwrite" replaces entire content, "append" adds to the end of the file'
        }
      },
      required: ["path", "content", "mode"]
    };
    this.isMutation = true;
  }
  async execute(args, app) {
    try {
      const file = app.vault.getAbstractFileByPath(args.path);
      if (!file || !(file instanceof import_obsidian9.TFile)) {
        return {
          success: false,
          output: "",
          error: `File not found at path: ${args.path}`
        };
      }
      if (args.mode === "append") {
        await app.vault.append(file, "\n" + args.content);
        return {
          success: true,
          output: `Successfully appended content to ${file.path}.`
        };
      } else {
        await app.vault.modify(file, args.content);
        return {
          success: true,
          output: `Successfully overwritten content of ${file.path}.`
        };
      }
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error patching file ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/list-dir.ts
var import_obsidian10 = require("obsidian");
var VaultListDirTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_list_dir";
    this.description = "Lists all files and subfolders within a given Vault folder path.";
    this.parameters = {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: 'Relative path of the directory (use "" or "/" for root directory)'
        }
      },
      required: ["path"]
    };
    this.isMutation = false;
  }
  async execute(args, app) {
    try {
      const folderPath = (args.path || "").replace(/^\//, "");
      const folder = folderPath === "" ? app.vault.getRoot() : app.vault.getAbstractFileByPath(folderPath);
      if (!folder || !(folder instanceof import_obsidian10.TFolder)) {
        return {
          success: false,
          output: "",
          error: `Directory not found at path: "${args.path}"`
        };
      }
      const items = folder.children.map((child) => ({
        name: child.name,
        path: child.path,
        type: child instanceof import_obsidian10.TFolder ? "folder" : "file"
      }));
      return {
        success: true,
        output: JSON.stringify(items, null, 2)
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error listing directory ${args.path}: ${e.message}`
      };
    }
  }
};

// src/tools/vault/search-notes.ts
var VaultSearchNotesTool = class extends AgentTool {
  constructor() {
    super(...arguments);
    this.name = "vault_search_notes";
    this.description = "Searches for notes in the Vault matching a search query string or keyword.";
    this.parameters = {
      type: "object",
      properties: {
        query: {
          type: "string",
          description: "Keyword or tag to search for in note paths or titles"
        }
      },
      required: ["query"]
    };
    this.isMutation = false;
  }
  async execute(args, app) {
    try {
      const queryLower = (args.query || "").toLowerCase();
      const files = app.vault.getMarkdownFiles();
      const matched = files.filter((file) => file.path.toLowerCase().includes(queryLower) || file.basename.toLowerCase().includes(queryLower)).map((file) => ({
        name: file.name,
        path: file.path,
        size: file.stat.size,
        mtime: file.stat.mtime
      })).slice(0, 20);
      return {
        success: true,
        output: JSON.stringify(matched, null, 2)
      };
    } catch (e) {
      return {
        success: false,
        output: "",
        error: `Error searching notes for "${args.query}": ${e.message}`
      };
    }
  }
};

// src/tools/registry.ts
var ToolRegistry = class {
  constructor() {
    this.tools = /* @__PURE__ */ new Map();
    this.registerTool(new VaultReadFileTool());
    this.registerTool(new VaultCreateFileTool());
    this.registerTool(new VaultPatchFileTool());
    this.registerTool(new VaultListDirTool());
    this.registerTool(new VaultSearchNotesTool());
  }
  registerTool(tool) {
    this.tools.set(tool.name, tool);
  }
  getTool(name) {
    return this.tools.get(name);
  }
  /**
   * Returns all registered tools as deterministically sorted ToolSchemas.
   */
  getSchemas() {
    const rawSchemas = Array.from(this.tools.values()).map((t) => t.toSchema());
    return sortToolSchemasDeterministically(rawSchemas);
  }
  async executeTool(name, args, app) {
    const tool = this.getTool(name);
    if (!tool) {
      return {
        success: false,
        output: "",
        error: `Unknown tool name: "${name}"`
      };
    }
    return await tool.execute(args, app);
  }
};

// src/utils/markdown-exporter.ts
var MarkdownExporter = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Exports conversation history to a formatted Markdown note in the "Agent Chats/" Vault folder.
   */
  async exportChatToMarkdown(messages, modelName) {
    const folderPath = "Agent Chats";
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await this.app.vault.createFolder(folderPath);
    }
    const now = /* @__PURE__ */ new Date();
    const dateStr = now.toISOString().replace(/T/, " ").replace(/\..+/, "");
    const fileDateStr = now.toISOString().slice(0, 10) + "-" + now.toTimeString().slice(0, 5).replace(":", "-");
    const filename = `${folderPath}/Agent Chat ${fileDateStr}.md`;
    let mdContent = `---
tags:
  - agent-chat
created: ${dateStr}
model: ${modelName}
---

# \u{1F916} Agent Chat Session (${dateStr})

`;
    for (const msg of messages) {
      if (msg.role === "user") {
        mdContent += `### \u{1F464} User
${msg.content}

`;
      } else if (msg.role === "assistant") {
        if (msg.content) {
          mdContent += `### \u{1F916} Assistant
${msg.content}

`;
        }
        if (msg.tool_calls && msg.tool_calls.length > 0) {
          mdContent += `> \u{1F6E0}\uFE0F **Tool Calls Requested:**
`;
          for (const tc of msg.tool_calls) {
            mdContent += `> - \`${tc.function.name}\` \`\`\`json
${tc.function.arguments}
\`\`\`
`;
          }
          mdContent += `
`;
        }
      } else if (msg.role === "tool") {
        mdContent += `> \u2699\uFE0F **Tool Result (${msg.name}):**
\`\`\`
${msg.content}
\`\`\`

`;
      }
    }
    const createdFile = await this.app.vault.create(filename, mdContent);
    return createdFile.path;
  }
};

// src/ui/components/confirmation-modal.ts
var import_obsidian11 = require("obsidian");
var ConfirmationModal = class extends import_obsidian11.Modal {
  constructor(app, toolCall, onResult) {
    super(app);
    this.toolCall = toolCall;
    this.onResult = onResult;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("harness-modal-content");
    contentEl.createEl("h3", { text: "\u26A0\uFE0F File Action Confirmation" });
    contentEl.createEl("p", {
      text: `The AI Agent is requesting permission to execute tool: "${this.toolCall.function.name}".`
    });
    const codeBlock = contentEl.createEl("pre");
    codeBlock.createEl("code", { text: this.toolCall.function.arguments });
    new import_obsidian11.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Deny").onClick(() => {
        this.onResult(false);
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Approve & Execute").setCta().onClick(() => {
        this.onResult(true);
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/chat-view.ts
var HARNESS_VIEW_TYPE = "harness-chat-view";
var HarnessChatView = class extends import_obsidian12.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.conversationHistory = [];
    this.currentProviderId = "openrouter";
    this.currentModel = "anthropic/claude-3.7-sonnet";
    this.plugin = plugin;
    this.toolRegistry = new ToolRegistry();
    this.agentHarness = new AgentHarness(this.app, this.plugin.settings, this.toolRegistry);
    this.exporter = new MarkdownExporter(this.app);
    this.currentProviderId = this.plugin.settings.activeProviderId || "openrouter";
    this.currentModel = this.plugin.settings.activeModel || "anthropic/claude-3.7-sonnet";
  }
  getViewType() {
    return HARNESS_VIEW_TYPE;
  }
  getDisplayText() {
    return "Harness Bot";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("harness-chat-container");
    const headerEl = container.createEl("div", { cls: "harness-chat-header" });
    headerEl.createEl("span", { text: "\u{1F916} Harness Bot", cls: "harness-title" });
    const selectorsEl = headerEl.createEl("div", { cls: "harness-chat-header-actions" });
    this.providerSelectEl = selectorsEl.createEl("select");
    this.refreshProviderDropdown();
    this.providerSelectEl.addEventListener("change", () => {
      this.currentProviderId = this.providerSelectEl.value;
      this.refreshModelDropdown();
    });
    this.modelSelectEl = selectorsEl.createEl("select");
    this.refreshModelDropdown();
    this.modelSelectEl.addEventListener("change", () => {
      this.currentModel = this.modelSelectEl.value;
    });
    const exportBtn = selectorsEl.createEl("button", { text: "\u{1F4E4} Export" });
    exportBtn.addEventListener("click", async () => {
      if (this.conversationHistory.length === 0) {
        new import_obsidian12.Notice("No chat history to export.");
        return;
      }
      try {
        const exportedPath = await this.exporter.exportChatToMarkdown(
          this.conversationHistory,
          this.currentModel
        );
        new import_obsidian12.Notice(`Chat exported to ${exportedPath}`);
      } catch (e) {
        new import_obsidian12.Notice(`Export failed: ${e.message}`);
      }
    });
    const clearBtn = selectorsEl.createEl("button", { text: "\u{1F5D1}\uFE0F Clear" });
    clearBtn.addEventListener("click", () => {
      this.conversationHistory = [];
      this.renderMessages();
    });
    this.messagesContainerEl = container.createEl("div", { cls: "harness-chat-messages" });
    const inputAreaEl = container.createEl("div", { cls: "harness-chat-input-area" });
    const inputContainerEl = inputAreaEl.createEl("div", { cls: "harness-chat-input-container" });
    this.inputTextAreaEl = inputContainerEl.createEl("textarea", {
      cls: "harness-chat-textarea",
      placeholder: "Ask Harness Bot to read, search, plan, or create notes..."
    });
    this.sendButtonEl = inputContainerEl.createEl("button", { text: "Send", cls: "mod-cta" });
    const handleSend = async () => {
      const text = this.inputTextAreaEl.value.trim();
      if (!text)
        return;
      this.inputTextAreaEl.value = "";
      this.sendButtonEl.disabled = true;
      const userMsg = { role: "user", content: text };
      this.conversationHistory.push(userMsg);
      this.renderMessages();
      const streamingMsgEl = this.messagesContainerEl.createEl("div", {
        cls: "harness-message harness-message-assistant"
      });
      streamingMsgEl.createEl("div", { text: `\u{1F916} Harness Bot (${this.currentModel})`, cls: "harness-message-header" });
      const textContentEl = streamingMsgEl.createEl("div", { cls: "harness-message-body" });
      try {
        const updatedHistory = await this.agentHarness.runTurn(
          this.conversationHistory,
          (event) => {
            if (event.type === "chunk" && event.content) {
              textContentEl.setText(event.content);
              this.messagesContainerEl.scrollTop = this.messagesContainerEl.scrollHeight;
            } else if (event.type === "tool_call" && event.toolCall) {
              const card = this.messagesContainerEl.createEl("div", { cls: "harness-tool-card" });
              card.createEl("div", {
                text: `\u{1F6E0}\uFE0F Tool requested: ${event.toolCall.function.name}`,
                cls: "harness-tool-title"
              });
            }
          },
          (toolCall) => {
            return new Promise((resolve) => {
              new ConfirmationModal(this.app, toolCall, resolve).open();
            });
          },
          this.currentProviderId,
          this.currentModel
        );
        this.conversationHistory = updatedHistory;
      } catch (err) {
        new import_obsidian12.Notice(`Agent error: ${err.message}`);
        textContentEl.setText(`\u26A0\uFE0F Error: ${err.message}`);
      } finally {
        this.sendButtonEl.disabled = false;
        this.renderMessages();
      }
    };
    this.sendButtonEl.addEventListener("click", handleSend);
    this.inputTextAreaEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        handleSend();
      }
    });
    this.renderMessages();
  }
  refreshProviderDropdown() {
    if (!this.providerSelectEl)
      return;
    this.providerSelectEl.empty();
    for (const p of this.plugin.settings.providers) {
      const opt = this.providerSelectEl.createEl("option", { value: p.id, text: p.name });
      if (p.id === this.currentProviderId)
        opt.selected = true;
    }
  }
  refreshModelDropdown() {
    if (!this.modelSelectEl)
      return;
    this.modelSelectEl.empty();
    const currentProv = this.plugin.settings.providers.find((p) => p.id === this.currentProviderId);
    const models = currentProv?.models || [];
    for (const m of models) {
      const opt = this.modelSelectEl.createEl("option", { value: m, text: m });
      if (m === this.currentModel)
        opt.selected = true;
    }
    if (models.length > 0 && !models.includes(this.currentModel)) {
      this.currentModel = models[0];
    }
  }
  renderMessages() {
    if (!this.messagesContainerEl)
      return;
    this.messagesContainerEl.empty();
    if (this.conversationHistory.length === 0) {
      const emptyEl = this.messagesContainerEl.createEl("div", {
        cls: "harness-empty-state",
        text: "No active conversation. Type a message below to start Obsidian Harness Bot."
      });
      emptyEl.style.opacity = "0.6";
      emptyEl.style.textAlign = "center";
      emptyEl.style.padding = "32px 16px";
      return;
    }
    for (const msg of this.conversationHistory) {
      if (msg.role === "user") {
        const msgEl = this.messagesContainerEl.createEl("div", { cls: "harness-message harness-message-user" });
        msgEl.createEl("div", { text: "\u{1F464} You", cls: "harness-message-header" });
        msgEl.createEl("div", {
          text: typeof msg.content === "string" ? msg.content : JSON.stringify(msg.content || ""),
          cls: "harness-message-body"
        });
      } else if (msg.role === "assistant") {
        if (msg.content) {
          const msgEl = this.messagesContainerEl.createEl("div", { cls: "harness-message harness-message-assistant" });
          msgEl.createEl("div", { text: "\u{1F916} Harness Bot", cls: "harness-message-header" });
          msgEl.createEl("div", {
            text: typeof msg.content === "string" ? msg.content : JSON.stringify(msg.content || ""),
            cls: "harness-message-body"
          });
        }
        if (msg.tool_calls) {
          for (const tc of msg.tool_calls) {
            const card = this.messagesContainerEl.createEl("div", { cls: "harness-tool-card" });
            card.createEl("div", { text: `\u{1F6E0}\uFE0F Tool: ${tc.function.name}`, cls: "harness-tool-title" });
            const argsPre = card.createEl("pre");
            argsPre.createEl("code", { text: tc.function.arguments });
          }
        }
      } else if (msg.role === "tool") {
        const card = this.messagesContainerEl.createEl("div", { cls: "harness-tool-card" });
        card.createEl("div", { text: `\u2699\uFE0F Tool Output (${msg.name})`, cls: "harness-tool-title" });
        const outPre = card.createEl("pre");
        outPre.createEl("code", {
          text: typeof msg.content === "string" ? msg.content : JSON.stringify(msg.content || "")
        });
      }
    }
    this.messagesContainerEl.scrollTop = this.messagesContainerEl.scrollHeight;
  }
  async onClose() {
  }
};

// src/main.ts
var HarnessPlugin = class extends import_obsidian13.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(HARNESS_VIEW_TYPE, (leaf) => new HarnessChatView(leaf, this));
    this.addRibbonIcon("bot", "Open Obsidian Harness Bot", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-obsidian-harness-bot",
      name: "Open Obsidian Harness Bot",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new HarnessSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(HARNESS_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: HARNESS_VIEW_TYPE,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (!this.settings.providers || this.settings.providers.length === 0) {
      this.settings.providers = DEFAULT_SETTINGS.providers;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
